% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,int,int,int,array(int),int).
:- mode new1(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new1(A,B,C,D,E,F) :- 
          constr((select(E,A)=F&(select(E,A)=C&(C-F>=1&(D-A>=1&(A>=0&G=0)))))).
new1(A,B,C,D,E,F) :- 
          constr((select(E,A)=F&(select(E,A)=C&(D-A>=1&(A>=0&(C-F=< - 1&G=0)))))).
new1(A,B,C,D,E,F) :- new1(G,B,C,D,E,F), 
          constr((select(E,A)=H&(D-A>=1&(C-H=< - 1&(I=1&G=1+A))))).
new1(A,B,C,D,E,F) :- new1(G,B,C,D,E,F), 
          constr((select(E,A)=H&(C-H>=1&(D-A>=1&(I=1&G=1+A))))).
new1(A,B,C,D,E,F) :- 
          constr((select(E,B)=F&(C-F>=1&(D-B>=1&(A-D>=0&(B>=0&G=0)))))).
new1(A,B,C,D,E,F) :- 
          constr((select(E,B)=F&(D-B>=1&(A-D>=0&(B>=0&(C-F=< - 1&G=0)))))).
incorrect :- new1(A,B,C,D,E,F), constr((D>=1&(A=0&(B= - 1&G=1)))).

