% Automatically generated by smt2map




:- pred inv1(int,int,int,int,int,int,int,int,int,int).
:- mode inv1(in,in,in,in,in,in,in,in,in,in).
:- pred inv3(int,int,int).
:- mode inv3(in,in,in).
:- pred inv2(int,int,int,int,int,int,int,int,int,int).
:- mode inv2(in,in,in,in,in,in,in,in,in,in).
:- pred inv4(int,int,int).
:- mode inv4(in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv3(A,B,C) :- inv1(D,E,F,A,G,H,I,J,K,L), 
          constr((and(M=not(D+ - 1*F>=1),and(I=K,and(H= - 1+C,and(G=1+B,and(M,and(A+ - 1*H>=1,J=L)))))))).
inv1(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(inv1(A,B,C,K,L,M,G,H,I,J),and(inv3(D,E,F),and(and(G=I,N,K+ - 1*M>=1,O,H=J),N=not(A+ - 1*C>=1),O=not(F+ - 1*D>=1)))))).
inv3(A,B,C) :- 
          constr((and(inv1(D,E,F,G,H,I,J,K,L,M),and(inv3(N,O,C),and(and(J=L,O= - 1+B,N= - 1+A,C+ - 1*N>=1,G+ - 1*I>=1,P,K=M),P=not(D+ - 1*F>=1)))))).
inv2(A,B,C,D,E,F,G,H,I,J) :- inv1(A,K,L,D,M,N,G,H,I,J), 
          constr((and(M=1+E,and(L= - 1+C,and(K=1+B,and(H=J,and(G=I,and(A+ - 1*L>=1,and(D+ - 1*N>=1,N= - 1+F))))))))).
inv1(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(inv1(K,L,M,N,O,P,G,H,I,J),and(inv2(A,B,C,D,E,F,G,H,I,J),and(and(G=I,Q,N+ - 1*P>=1,K+ - 1*M>=1,R,H=J),Q=not(C+ - 1*A>=1),R=not(F+ - 1*D>=1)))))).
inv2(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(inv1(K,L,M,N,O,P,G,H,I,J),and(inv2(A,B,C,Q,R,F,G,H,I,J),and(and(Q= - 1+D,H=J,G=I,S,F+ - 1*Q>=1,N+ - 1*P>=1,K+ - 1*M>=1,R= - 1+E),S=not(C+ - 1*A>=1)))))).
inv2(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(inv1(K,L,M,N,O,P,G,H,I,J),and(inv2(Q,R,C,S,T,F,G,H,I,J),and(H=J,T= - 1+E,S= - 1+D,R= - 1+B,Q= - 1+A,C+ - 1*Q>=1,F+ - 1*S>=1,N+ - 1*P>=1,K+ - 1*M>=1,G=I))))).
inv2(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(inv1(K,L,M,N,O,P,G,H,I,J),and(inv2(Q,R,C,D,E,F,G,H,I,J),and(and(Q= - 1+A,H=J,G=I,C+ - 1*Q>=1,S,N+ - 1*P>=1,K+ - 1*M>=1,R= - 1+B),S=not(F+ - 1*D>=1)))))).
inv4(A,B,C) :- 
          constr((and(inv1(D,E,F,G,H,I,J,K,L,M),and(inv4(N,O,C),and(and(J=L,O= - 1+B,N= - 1+A,C+ - 1*N>=1,P,D+ - 1*F>=1,K=M),P=not(G+ - 1*I>=1)))))).
inv1(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(inv1(K,L,M,D,E,F,G,H,I,J),and(inv4(A,B,C),and(and(G=I,K+ - 1*M>=1,N,O,H=J),N=not(D+ - 1*F>=1),O=not(C+ - 1*A>=1)))))).
inv4(A,B,C) :- inv1(A,D,E,F,G,H,I,J,K,L), 
          constr((and(M=not(F+ - 1*H>=1),and(I=K,and(E= - 1+C,and(D=1+B,and(M,and(A+ - 1*E>=1,J=L)))))))).
inv1(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(C=0,and(B=E,and(A=D,and(F=0,and(G=A,and(H=B,and(I=D,J=E))))))))).
ff :- inv1(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(G=I,not(B=E),K,L,H=J),and(K=not(D+ - 1*F>=1),L=not(A+ - 1*C>=1))))).

