% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,int,array(int),array(int),array(int),array(int),int,int,int,int,int,int,int).
:- mode new1(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new2(int,int,array(int),array(int),array(int),array(int),int,int,int,int,int,int,int).
:- mode new2(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new3(int,int,array(int),array(int),array(int),array(int),int,int,int,int,int,int,int).
:- mode new3(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new3(N,B,O,P,E,F,Q,H,I,J,K,L,M), 
          constr((store(D,A,Q)=P&(store(C,A,R)=O&(select(D,A)=R&(select(C,A)=Q&(B-A>=1&(S=1&N=1+A))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((select(C,J)=H&(select(E,J)=I&(B-J>=1&(A-B>=0&(J>=0&(I-H=< - 1&N=0))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((select(C,J)=H&(select(E,J)=I&(I-H>=1&(B-J>=1&(A-B>=0&(J>=0&N=0))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((select(D,J)=K&(select(F,J)=L&(B-J>=1&(A-B>=0&(J>=0&(L-K=< - 1&N=0))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((select(D,J)=K&(select(F,J)=L&(L-K>=1&(B-J>=1&(A-B>=0&(J>=0&N=0))))))).
new2(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new2(N,B,O,P,E,F,Q,H,I,J,K,L,M), 
          constr((store(D,A,Q)=P&(store(C,A,R)=O&(select(D,A)=R&(select(C,A)=Q&(B-A>=1&(S=1&N=1+A))))))).
new2(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new3(N,B,C,D,E,F,G,H,I,J,K,L,M), 
          constr((A-B>=0&N=0)).
new1(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new1(N,B,C,D,O,P,G,H,I,J,K,L,M), 
          constr((store(F,A,Q)=P&(store(E,A,R)=O&(select(D,A)=Q&(select(C,A)=R&(B-A>=1&(S=1&N=1+A))))))).
new1(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new2(N,B,C,D,E,F,G,H,I,J,K,L,M), 
          constr((A-B>=0&N=0)).
incorrect :- new1(A,B,C,D,E,F,G,H,I,J,K,L,M), constr((B>=1&(A=0&N=1))).

