% Automatically generated by smt2map




:- pred new6(int,int,int,int,int,int).
:- mode new6(in,in,in,in,in,in).
:- pred new5(int,int,int,int,int).
:- mode new5(in,in,in,in,in).
:- pred new4(int,int,int,int,int).
:- mode new4(in,in,in,in,in).
:- pred new3(int,int,int,int,int).
:- mode new3(in,in,in,in,in).
:- pred new2(int,int,int,int,int).
:- mode new2(in,in,in,in,in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new6(A,B,C,D,E,F) :- constr((G=0&(H=0&A=0))).
new5(A,B,C,D,E) :- new6(F,A,B,C,D,E), constr((E=<0&(G=0&F=1))).
new5(A,B,C,D,E) :- new6(F,A,B,C,D,E), constr((E>=1&(G=0&F=0))).
new4(A,B,C,D,E) :- new3(A,B,C,D,E), constr((true)).
new3(A,B,C,D,E) :- new4(A,F,C,D,E), constr((C-B>=1&(G=1&F=1+B))).
new3(A,B,C,D,E) :- new5(A,B,C,D,E), constr((B-C>=0)).
new2(A,B,C,D,E) :- new3(A,B,C,F,E), constr((A>=1&(F=1&G=0))).
new2(A,B,C,D,E) :- new3(A,B,C,F,E), constr((A=<0&(F=2&G=0))).
new1 :- new2(A,B,C,D,E), constr((B=0&E=0)).
incorrect :- new1, constr((true)).

