% Automatically generated by smt2map




:- pred block_8_return_function_deposit__38_39_0(int,int,abi_type,crypto_type,tx_type,state_type,int,int,state_type,int,int).
:- mode block_8_return_function_deposit__38_39_0(in,in,in,in,in,in,in,in,in,in,in).
:- pred block_9_function_deposit__38_39_0(int,int,abi_type,crypto_type,tx_type,state_type,int,int,state_type,int,int).
:- mode block_9_function_deposit__38_39_0(in,in,in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

block_9_function_deposit__38_39_0(A,B,C,D,E,F,G,H,I,J,K) :- 
          constr((and(and(and(true,not(L)),A=1),and(block_7_deposit_37_39_0(M,B,C,D,E,F,G,H,I,J,K),and(L=(N=O),and((true=>true),and(O=1,and((true=>true),and(N=1,and((true=>P),and(bytes_tuple_accessor_array(Q)=store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(store(const_array(int,0),0,111),1,110),2,108),3,121),4,32),5,116),6,104),7,101),8,32),9,111),10,119),11,110),12,101),13,114),14,32),15,99),16,97),17,110),18,32),19,100),20,101),21,112),22,111),23,115),24,105),25,116),and(bytes_tuple_accessor_length(Q)=26,and(P=(R=S),and((true=>and(S>=0,S=<1461501637330902918203684832716283019655932542975)),and(S=K,and((true=>and(R>=0,R=<1461501637330902918203684832716283019655932542975)),and(R='msg.sender'(E),true))))))))))))))))).

