% Automatically generated by smt2map




:- pred new64(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new64(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new2(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new2(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new63(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new63(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new62(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new62(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new61(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new61(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new60(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new60(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new59(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new59(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new58(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new58(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new57(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new57(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new56(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new56(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new55(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new55(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new54(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new54(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new53(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new53(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new52(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new52(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new51(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new51(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new50(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new50(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new49(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new49(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new48(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new48(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new47(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new47(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new46(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new46(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new45(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new45(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new44(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new44(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new43(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new43(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new42(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new42(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new41(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new41(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new40(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new40(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new39(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new39(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new38(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new38(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new37(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new37(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new36(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new36(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new35(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new35(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new34(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new34(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new33(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new33(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new32(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new32(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new31(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new31(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new30(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new30(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new29(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new29(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new28(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new28(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new27(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new27(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new26(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new26(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new25(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new25(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new24(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new24(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new23(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new23(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new22(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new22(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new21(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new21(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new20(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new20(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new19(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new19(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new18(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new18(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new17(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new17(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new16(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new16(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new15(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new15(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new14(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new14(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new13(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new13(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new12(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new12(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new11(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new11(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new10(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new10(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new9(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new9(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new8(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new8(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new7(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new7(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new6(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new6(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new5(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new5(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new4(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new4(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new3(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new3(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new64(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(U,V,C,W,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(A>=1,and(W=1,and(X=1,and(V=1+B,and(Y=1,and(U= - 1+A,Z=1)))))))).
new63(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new64(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(D=<0,U=0))).
new62(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(U,V,C,D,W,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(A>=1,and(W=1,and(X=1,and(V=1+B,and(Y=1,and(U= - 1+A,Z=1)))))))).
new61(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new62(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(E=<0,U=0))).
new60(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(A,B,U,D,V,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(C>=1,and(V=0,and(W=1,and(U= - 1+C,X=1)))))).
new59(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new60(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(E=<1,U=1))).
new58(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(U,V,C,D,E,W,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(A>=1,and(W=1,and(X=1,and(V=1+B,and(Y=1,and(U= - 1+A,Z=1)))))))).
new57(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new58(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(F=<0,U=0))).
new56(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(A,B,U,D,E,V,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(C>=1,and(V=0,and(W=1,and(U= - 1+C,X=1)))))).
new55(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new56(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(F=<1,U=1))).
new54(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(U,V,C,D,E,F,W,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(A>=1,and(X=1,and(W=1+G,and(Y=1,and(V=1+B,and(Z=1,and(U= - 1+A,A1=1))))))))).
new53(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new54(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(G=<0,U=0))).
new52(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(A,B,U,D,E,F,V,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(C>=1,and(W=1,and(V= - 1+G,and(X=1,and(U= - 1+C,Y=1))))))).
new51(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new52(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(G=<1,U=1))).
new50(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(U,B,C,D,E,F,G,V,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H=<0,and(V=1,and(W=1,and(U=1+A,X=0)))))).
new49(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(A,U,C,D,E,F,G,V,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(B>=1,and(V=2,and(W=1,and(U= - 1+B,X=1)))))).
new48(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new49(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H=<1,U=1))).
new47(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(A,B,U,D,E,F,G,V,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H=<2,and(V=3,and(W=1,and(U=1+C,X=2)))))).
new46(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(A,B,C,D,E,F,G,U,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,and(W=0,C=0))))).
new45(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new46(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H=<3,U=3))).
new44(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new2(A,B,U,V,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(C>=1,and(V=0,and(W=1,and(U= - 1+C,X=1)))))).
new43(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new44(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(D=<1,U=1))).
new42(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new43(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(D>=1,U=1))).
new41(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new45(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H>=3,U=3))).
new40(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new41(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(I>=1,U=0))).
new40(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new41(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(I=< - 1,U=0))).
new40(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new42(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,I=0)))).
new39(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new40(A,B,C,D,E,F,G,H,U,J,K,L,M,N,O,P,Q,R,S,T), constr((true)).
new38(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new47(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H>=2,U=2))).
new37(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new38(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(J>=1,U=0))).
new37(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new38(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(J=< - 1,U=0))).
new37(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new39(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,J=0)))).
new36(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new37(A,B,C,D,E,F,G,H,I,U,K,L,M,N,O,P,Q,R,S,T), constr((true)).
new35(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new48(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H>=1,U=1))).
new34(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new35(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(K>=1,U=0))).
new34(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new35(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(K=< - 1,U=0))).
new34(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new36(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,K=0)))).
new33(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new34(A,B,C,D,E,F,G,H,I,J,U,L,M,N,O,P,Q,R,S,T), constr((true)).
new32(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new50(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H>=0,U=0))).
new31(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new32(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(L>=1,U=0))).
new31(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new32(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(L=< - 1,U=0))).
new31(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new33(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,L=0)))).
new30(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new31(A,B,C,D,E,F,G,H,I,J,K,U,M,N,O,P,Q,R,S,T), constr((true)).
new29(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new51(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(G>=1,U=1))).
new28(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new29(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(M>=1,U=0))).
new28(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new29(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(M=< - 1,U=0))).
new28(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new30(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,M=0)))).
new27(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new28(A,B,C,D,E,F,G,H,I,J,K,L,U,N,O,P,Q,R,S,T), constr((true)).
new26(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new53(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(G>=0,U=0))).
new25(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new26(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(N>=1,U=0))).
new25(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new26(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(N=< - 1,U=0))).
new25(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new27(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,N=0)))).
new24(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new25(A,B,C,D,E,F,G,H,I,J,K,L,M,U,O,P,Q,R,S,T), constr((true)).
new23(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new55(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(F>=1,U=1))).
new22(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new23(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(O>=1,U=0))).
new22(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new23(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(O=< - 1,U=0))).
new22(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new24(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,O=0)))).
new21(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new22(A,B,C,D,E,F,G,H,I,J,K,L,M,N,U,P,Q,R,S,T), constr((true)).
new20(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new57(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(F>=0,U=0))).
new19(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new20(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(P>=1,U=0))).
new19(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new20(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(P=< - 1,U=0))).
new19(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new21(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,P=0)))).
new18(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new19(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,U,Q,R,S,T), constr((true)).
new17(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new59(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(E>=1,U=1))).
new16(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new17(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(Q>=1,U=0))).
new16(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new17(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(Q=< - 1,U=0))).
new16(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new18(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,Q=0)))).
new15(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new16(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,U,R,S,T), constr((true)).
new14(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new61(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(E>=0,U=0))).
new13(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new14(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(R>=1,U=0))).
new13(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new14(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(R=< - 1,U=0))).
new13(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new15(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,R=0)))).
new12(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new13(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,U,S,T), constr((true)).
new11(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new63(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(D>=0,U=0))).
new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new11(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(S>=1,U=0))).
new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new11(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(S=< - 1,U=0))).
new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new12(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,S=0)))).
new9(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) :- 
          constr((and(V=0,and(W=0,A=0)))).
new8(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new9(U,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H-C>=0,U=1))).
new8(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new9(U,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H-C=< - 1,U=0))).
new7(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) :- 
          constr((and(V=0,and(W=0,A=0)))).
new7(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) :- 
          new8(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U), 
          constr((and(A>=1,V=0))).
new7(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) :- 
          new8(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U), 
          constr((and(A=< - 1,V=0))).
new6(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new7(U,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H=<3,and(V=3,U=1)))).
new6(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new7(U,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H>=4,and(V=3,U=0)))).
new5(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,U,T), constr((true)).
new4(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new5(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(T>=1,U=0))).
new4(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new5(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(T=< - 1,U=0))).
new4(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new6(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(U=0,and(V=0,T=0)))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new4(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,U), constr((true)).
new2(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) :- 
          new3(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), constr((true)).
new1 :- new2(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T), 
          constr((and(H=0,and(G=0,and(F=0,and(E=0,and(D=0,and(C=0,and(B=0,A=0))))))))).
incorrect :- new1, constr((true)).

