; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int (Array Int Int) Int Int Int Int Int Int Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B (Array Int Int)) (C Int) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= L (+ 1 J)) (= M 1) (>= (- A J) 1) (>= (- N C) 0) (= (select B J) N) (= (select B J) O) (new1 A B O C E F G H I L K))
      (new1 A B C D E F G H I J K)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C Int) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) )
    (=>
      (and (= L (+ 1 J)) (= M 1) (<= (- D N) (- 1)) (>= (- A J) 1) (>= (- C O) 1) (= (select B J) O) (= (select B J) N) (= (select B J) P) (new1 A B C P E F G H I L K))
      (new1 A B C D E F G H I J K)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C Int) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= L (+ 1 J)) (= M 1) (>= (- A J) 1) (>= (- C N) 1) (>= (- D O) 0) (= (select B J) N) (= (select B J) O) (new1 A B C D E F G H I L K))
      (new1 A B C D E F G H I J K)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C Int) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) )
    (=>
      (and (= L 0) (<= (- C E) (- 1)) (>= F 0) (>= (- J A) 0) (>= (- A F) 1) (= (select B F) E))
      (new1 A B C D E F G H I J K)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C Int) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) )
    (=>
      (and (= L 0) (<= (- D H) (- 1)) (>= F 0) (>= (- J A) 0) (>= (- A F) 1) (>= (- C G) 1) (= (select B F) H) (= (select B F) G))
      (new1 A B C D E F G H I J K)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C Int) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) )
    (=>
      (and (= L 0) (<= (- D H) (- 1)) (<= (- C G) (- 1)) (>= F 0) (>= (- J A) 0) (>= (- A F) 1) (= (select B F) H) (= (select B F) G))
      (new1 A B C D E F G H I J K)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) (E Int) (F Int) (G Int) (H (Array Int Int)) (I Int) (J Int) (K Int) (L Int) (M Int) )
    (=>
      (and (= A 1) (= B 0) (= C 1) (= D 2) (>= E 1) (>= (- F G) 1) (= (select H B) G) (= (select H C) F) (new1 E H F G I J K L M D G))
      incorrect
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) (E Int) (F Int) (G Int) (H (Array Int Int)) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) )
    (=>
      (and (= A 1) (= B 0) (= C 1) (= D 2) (>= E 1) (>= (- F G) 0) (= (select H B) F) (= (select H C) G) (new1 E H F G I J K L M D N))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
