% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,array(int),int,int,int,int,int,int).
:- mode new1(in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new1(A,B,C,D,E,F,G,H) :- new1(A,B,I,D,E,F,G,H), 
          constr((select(B,C)=J&(D-C>=1&(J>=0&(K=1&(I=1+C&L=0)))))).
new1(A,B,C,D,E,F,G,H) :- new1(A,I,C,J,K,F,G,H), 
          constr((store(L,J,K)=I&(store(B,C,M)=L&(select(B,J)=M&(select(B,C)=K&(select(B,C)=N&(C-J=<0&(N=< - 1&(O=1&(P=1+J&(Q=0&(R=1+J&D=1+J)))))))))))).
new1(A,B,C,D,E,F,G,H) :- 
          constr((select(B,H)=G&(C-H>=1&(H>=0&(C-A=< - 1&(D-C=<0&(G=< - 1&(I=0&J=0)))))))).
new1(A,B,C,D,E,F,G,H) :- 
          constr((select(B,H)=F&(A-H>=1&(F>=0&(C-H=<0&(D-C=<0&I=0)))))).
incorrect :- new1(A,B,C,A,D,E,F,G), constr((A>=1&(C=0&H=1))).

