% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,int,array(int),array(int),array(int),array(int),int,int,int,int,int,int,int).
:- mode new1(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new2(int,int,array(int),array(int),array(int),array(int),int,int,int,int,int,int,int).
:- mode new2(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new3(int,int,array(int),array(int),array(int),array(int),int,int,int,int,int,int,int).
:- mode new3(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new3(N,B,O,P,E,F,Q,H,I,J,K,L,M), 
          constr((and(store(D,A,Q)=P,and(store(C,A,R)=O,and(select(D,A)=R,and(select(C,A)=Q,and(B-A>=1,and(S=1,N=1+A)))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((and(select(C,J)=H,and(select(E,J)=I,and(B-J>=1,and(A-B>=0,and(J>=0,and(I-H=< - 1,N=0)))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((and(select(C,J)=H,and(select(E,J)=I,and(I-H>=1,and(B-J>=1,and(A-B>=0,and(J>=0,N=0)))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((and(select(D,J)=K,and(select(F,J)=L,and(B-J>=1,and(A-B>=0,and(J>=0,and(L-K=< - 1,N=0)))))))).
new3(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          constr((and(select(D,J)=K,and(select(F,J)=L,and(L-K>=1,and(B-J>=1,and(A-B>=0,and(J>=0,N=0)))))))).
new2(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new2(N,B,O,P,E,F,Q,H,I,J,K,L,M), 
          constr((and(store(D,A,Q)=P,and(store(C,A,R)=O,and(select(D,A)=R,and(select(C,A)=Q,and(B-A>=1,and(S=1,N=1+A)))))))).
new2(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new3(N,B,C,D,E,F,G,H,I,J,K,L,M), 
          constr((and(A-B>=0,N=0))).
new1(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new1(N,B,C,D,O,P,G,H,I,J,K,L,M), 
          constr((and(store(F,A,Q)=P,and(store(E,A,R)=O,and(select(D,A)=Q,and(select(C,A)=R,and(B-A>=1,and(S=1,N=1+A)))))))).
new1(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new2(N,B,C,D,E,F,G,H,I,J,K,L,M), 
          constr((and(A-B>=0,N=0))).
incorrect :- new1(A,B,C,D,E,F,G,H,I,J,K,L,M), constr((and(B>=1,and(A=0,N=1)))).

