% Automatically generated by smt2map




:- pred inv_main_1(int,int,int,int,array(int),int,int,int,int,array(int)).
:- mode inv_main_1(in,in,in,in,in,in,in,in,in,in).
:- pred chc_comp_false.
:- pred inv_main_0(int,int,int,int,array(int),int,int,int,int,array(int)).
:- mode inv_main_0(in,in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_0(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(and(H= - 1+K,not(K=0),not(G=F),not(D=0),D=K,C=G,A=F,not(A=C),L,M,E=J,B=A,I=F),and(L=not(ite(G>=0,G,- 1*G)=<ite(F>=0,F,- 1*F)),M=not(ite(C>=0,C,- 1*C)=<ite(A>=0,A,- 1*A)))))).
inv_main_1(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(H= - 1+K,and(G=smt_plus(- 1,L,K),and(F=smt_plus(- 1,I,K),and(A=B+D,and(C=M+D,and(not(K=0),and(not(L=I),and(not(D=0),and(D=K,and(M=L,and(B=I,and(not(B=M),and(ite(L>=0,L,- 1*L)=<ite(I>=0,I,- 1*I),and(ite(M>=0,M,- 1*M)=<ite(B>=0,B,- 1*B),E=J)))))))))))))))).
inv_main_0(A,B,C,D,E,F,G,H,I,J) :- inv_main_0(K,B,L,M,N,O,P,Q,I,R), 
          constr((and(E=store(N,K,select(N,L)),and(H= - 1+Q,and(G=1+P,and(F=1+O,and(D= - 1+M,and(C=1+L,and(A=1+K,and(not(Q=0),and(not(M=1),J=store(R,O,select(R,P))))))))))))).
inv_main_0(A,B,C,D,E,F,G,H,I,J) :- inv_main_0(K,B,L,M,N,F,G,H,I,J), 
          constr((and(D= - 1+M,and(C=1+L,and(A=1+K,and(H=0,and(not(M=1),E=store(N,K,select(N,L))))))))).
inv_main_0(A,B,C,D,E,F,G,H,I,J) :- inv_main_0(A,B,C,D,E,K,L,M,I,N), 
          constr((and(H= - 1+M,and(G=1+L,and(F=1+K,and(not(M=0),and(D=1,J=store(N,K,select(N,L))))))))).
inv_main_1(A,B,C,D,E,F,G,H,I,J) :- inv_main_1(K,B,L,M,N,O,P,Q,I,R), 
          constr((and(S=(E=store(N,- 1+K,select(N,- 1+L))),and(S,and(H= - 1+Q,and(G= - 1+P,and(F= - 1+O,and(D= - 1+M,and(C= - 1+L,and(A= - 1+K,and(not(Q=0),and(not(M=1),J=store(R,O,select(R,P)))))))))))))).
inv_main_1(A,B,C,D,E,F,G,H,I,J) :- inv_main_1(K,B,L,M,N,F,G,H,I,J), 
          constr((and(O=(E=store(N,- 1+K,select(N,- 1+L))),and(D= - 1+M,and(C= - 1+L,and(A= - 1+K,and(H=0,and(not(M=1),O)))))))).
inv_main_1(A,B,C,D,E,F,G,H,I,J) :- inv_main_1(A,B,C,D,E,K,L,M,I,N), 
          constr((and(H= - 1+M,and(G= - 1+L,and(F= - 1+K,and(not(M=0),and(D=1,J=store(N,K,select(N,L))))))))).
chc_comp_false :- 
          constr((and(and(not(A=0),not(B=C),D=A,E=B,F=C,G,or(D=0,F=E),H=I),G=not(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C))))).
chc_comp_false :- 
          constr((and(not(A=0),and(not(B=C),and(D=A,and(E=B,and(F=C,and(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C),and(or(D=0,F=E),G=H))))))))).
chc_comp_false :- 
          constr((and(and(A=0,not(B=C),not(D=0),D=A,E=B,F=C,not(F=E),G,H,I=J),and(G=not(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C)),H=not(ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F)))))).
chc_comp_false :- 
          constr((and(and(A=0,not(B=C),not(D=0),D=A,E=B,F=C,not(F=E),ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C),G,H=I),G=not(ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F))))).
chc_comp_false :- 
          constr((and(and(A=B,not(C=0),C=D,E=A,F=B,not(F=E),G,H=I),G=not(ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F))))).
chc_comp_false :- 
          constr((and(and(not(A=0),not(B=C),not(D=0),D=A,E=B,F=C,not(F=E),ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C),G,H=I),G=not(ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F))))).
chc_comp_false :- 
          constr((and(and(A=0,not(B=C),not(D=0),D=A,E=B,F=C,not(F=E),G,ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F),H=I),G=not(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C))))).
chc_comp_false :- 
          constr((and(A=0,and(not(B=C),and(not(D=0),and(D=A,and(E=B,and(F=C,and(not(F=E),and(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C),and(ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F),G=H))))))))))).
chc_comp_false :- 
          constr((and(A=B,and(not(C=0),and(C=D,and(E=A,and(F=B,and(not(F=E),and(ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F),G=H))))))))).
chc_comp_false :- 
          constr((and(and(not(A=0),not(B=C),not(D=0),D=A,E=B,F=C,not(F=E),G,ite(E>=0,E,- 1*E)=<ite(F>=0,F,- 1*F),H=I),G=not(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C))))).
chc_comp_false :- 
          constr((and(and(A=0,not(B=C),D=A,E=B,F=C,G,or(not(H=I),not(F=C)),or(D=0,F=E),H=I),G=not(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C))))).
chc_comp_false :- 
          constr((and(A=0,and(not(B=C),and(D=A,and(E=B,and(F=C,and(ite(B>=0,B,- 1*B)=<ite(C>=0,C,- 1*C),and(or(not(G=H),not(F=C)),and(or(D=0,F=E),G=H)))))))))).
chc_comp_false :- 
          constr((and(A=B,and(C=D,and(E=A,and(F=B,and(or(not(G=H),not(F=B)),and(or(C=0,F=E),G=H)))))))).
chc_comp_false :- inv_main_0(A,B,C,D,E,F,G,H,I,J), 
          constr((and(K=not(store(E,A,select(E,C))=store(J,F,select(J,G))),and(D=1,and(or(not(B=I),K),H=0))))).
chc_comp_false :- inv_main_1(A,B,C,D,E,F,G,H,I,J), 
          constr((and(K=(store(E,- 1+A,select(E,- 1+C))=store(J,F,select(J,G))),and(D=1,and(or(not(B=I),not(K)),H=0))))).
ff :- chc_comp_false, constr((true)).

