% Automatically generated by smt2map




:- pred 'main@_bb'(int,int,int,array(int),int,array(int)).
:- mode 'main@_bb'(in,in,in,in,in,in).
:- pred 'main@verifier.error.split'.
:- pred 'main@_bb12'(int,array(int),int,array(int),int,int,int,int).
:- mode 'main@_bb12'(in,in,in,in,in,in,in,in).
:- pred 'main@_bb4'(int,int,array(int),int,int,array(int)).
:- mode 'main@_bb4'(in,in,in,in,in,in).
:- pred 'main@_bb9'(int,array(int),int,array(int),int,int).
:- mode 'main@_bb9'(in,in,in,in,in,in).
:- pred 'main@_bb7'(int,array(int),int,array(int),int).
:- mode 'main@_bb7'(in,in,in,in,in).
:- pred 'main@entry'(int).
:- mode 'main@entry'(in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A) :- constr((true)).
'main@_bb'(A,B,C,D,E,F) :- 'main@entry'(A), 
          constr((and(not(E=<0),and(or(not(G),not(H),I=0),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=K),and(or(not(G),not(H),D=J),and(or(not(H),and(G,H)),and(H=true,not(B=<0)))))))))).
'main@_bb'(A,B,C,D,E,F) :- 'main@_bb'(A,B,G,H,E,F), 
          constr((and(or(not(I=<0),not(J),B=<0),and(or(not(K),not(J),L),and(or(not(J),not(M),N=O),and(or(not(J),not(M),C=N),and(or(not(J),not(M),P=Q),and(or(not(J),not(M),D=P),and(or(not(M),and(J,M)),and(or(not(J),R=A),and(or(not(J),I=B+G),and(or(not(J),O=1+G),and(or(not(J),Q=store(H,I,S)),and(or(not(J),not(B=<0)),and(or(not(J),and(J,K)),and(M=true,not((5=<G)=L))))))))))))))))).
'main@_bb4'(A,B,C,D,E,F) :- 'main@_bb'(A,B,G,C,D,H), 
          constr((and(or(not(I=<0),not(J),B=<0),and(or(not(J),not(K),not(L)),and(or(not(J),not(M),N=0),and(or(not(J),not(M),E=N),and(or(not(J),not(M),O=H),and(or(not(J),not(M),F=O),and(or(not(M),and(J,M)),and(or(not(J),P=(Q=0)),and(or(not(J),I=4+B),and(or(not(J),Q=select(C,I)),and(or(not(J),not(B=<0)),and(or(not(J),and(J,L)),and(or(not(J),P),and(M=true,not((5=<G)=K))))))))))))))))).
'main@_bb4'(A,B,C,D,E,F) :- 'main@_bb4'(A,B,C,D,G,H), 
          constr((and(or(not(I),not(J=<0),D=<0),and(or(not(K),not(I),L),and(or(not(I),not(M),N=O),and(or(not(I),not(M),E=N),and(or(not(I),not(M),P=Q),and(or(not(I),not(M),F=P),and(or(not(M),and(I,M)),and(or(not(I),R=A),and(or(not(I),J=D+G),and(or(not(I),O=1+G),and(or(not(I),Q=store(H,J,S)),and(or(not(I),not(D=<0)),and(or(not(I),and(I,K)),and(M=true,not((5=<G)=L))))))))))))))))).
'main@_bb7'(A,B,C,D,E) :- 'main@_bb4'(F,A,B,C,G,D), 
          constr((and(or(not(H),not(I=<0),C=<0),and(or(not(H),not(J),not(K)),and(or(not(H),not(L),M=0),and(or(not(H),not(L),E=M),and(or(not(H),N=(O=0)),and(or(not(H),O=select(D,I)),and(or(not(H),I=4+C),and(or(not(H),not(C=<0)),and(or(not(H),and(H,K)),and(or(not(H),N),and(or(not(L),and(L,H)),and(L=true,not((5=<G)=J))))))))))))))).
'main@_bb7'(A,B,C,D,E) :- 'main@_bb7'(A,B,C,D,F), 
          constr((and(G=A+F,and(H=select(B,G),and(not(A=<0),and(or(not(I),not(J),not(K)),and(or(not(I),not(L),M=N),and(or(not(I),not(L),E=M),and(or(not(G=<0),A=<0),and(or(not(I),N=1+F),and(or(not(I),and(I,J)),and(or(not(L),and(L,I)),and(L=true,K=(H=0)))))))))))))).
'main@_bb9'(A,B,C,D,E,F) :- 'main@_bb7'(A,B,C,D,F), 
          constr((and(G=A+F,and(H=select(B,G),and(not(A=<0),and(or(not(I),not(J),K=0),and(or(not(I),not(J),E=K),and(or(not(I),not(J),L),and(or(A=<0,not(G=<0)),and(or(not(J),and(I,J)),and(J=true,L=(H=0)))))))))))).
'main@_bb9'(A,B,C,D,E,F) :- 'main@_bb9'(A,B,C,D,G,F), 
          constr((and(H=C+G,and(I=select(D,H),and(not(C=<0),and(or(not(J),not(K),not(L)),and(or(not(J),not(M),N=O),and(or(not(J),not(M),E=N),and(or(not(H=<0),C=<0),and(or(not(M),and(J,M)),and(or(not(J),O=1+G),and(or(not(J),and(J,L)),and(M=true,K=(I=0)))))))))))))).
'main@_bb12'(A,B,C,D,E,F,G,H) :- 'main@_bb9'(A,B,C,D,G,H), 
          constr((and(I=or(not(J),not((H=<G)=K)),and(L=select(D,M),and(M=C+G,and(not(C=<0),and(or(not(J),not(N),O=0),and(or(not(J),not(N),F=O),and(or(not(J),not(N),P=0),and(or(not(J),not(N),E=P),and(or(not(J),not(Q),R),and(or(C=<0,not(M=<0)),and(or(not(N),and(J,N)),and(I,and(or(not(J),and(J,Q)),and(or(not(J),not(K)),and(N=true,R=(L=0)))))))))))))))))).
'main@_bb12'(A,B,C,D,E,F,G,H) :- 'main@_bb12'(A,B,C,D,I,J,G,H), 
          constr((and(K=or(not(L),M=I+ - 1*N),and(not((H=<I)=O),and(P=and(Q,O),and(or(A=<0,not(L),not(R=<0)),and(or(C=<0,not(L),not(S=<0)),and(or(P,not(L),not(T)),and(or(not(L),not(U),V=W),and(or(not(L),not(U),F=V),and(or(not(L),not(U),X=Y),and(or(not(L),not(U),E=X),and(or(not(U),and(L,U)),and(or(not(L),Z=(A1=B1)),and(or(not(L),R=A+I),and(or(not(L),S=C+J),and(or(not(L),A1=select(B,R)),and(or(not(L),B1=select(D,S)),and(or(not(L),C1=1+J),and(or(not(L),N=ite(Z,0,J)),and(K,and(or(not(L),W=ite(Z,C1,0)),and(or(not(L),Y=1+M),and(or(not(L),not(A=<0)),and(or(not(L),not(C=<0)),and(or(not(L),and(L,T)),and(U=true,not((G=<J)=Q)))))))))))))))))))))))))))).
'main@verifier.error.split' :- 'main@_bb12'(A,B,C,D,E,F,G,H), 
          constr((and(I=or(not(J),not((F=<K)=L)),and(not((G=<F)=M),and(N=and(M,O),and(or(not(J),not(N),not(P)),and(or(not(Q),R=(S=0)),and(or(not(Q),and(T,Q)),and(or(not(Q),R),and(or(not(U),and(U,Q)),and(or(not(V),and(V,U)),and(or(not(W),and(W,V)),and(or(not(T),and(J,T)),and(I,and(or(not(J),not(L=X)),and(or(not(J),Y=or(X,L)),and(or(not(J),K= - 1+G),and(or(not(J),S=ite(Y,1,0)),and(or(not(J),and(J,P)),and(or(not(J),not(Z)),and(W=true,not((H=<E)=O)))))))))))))))))))))).
ff :- 'main@verifier.error.split', constr((true)).

