% Automatically generated by smt2map




:- pred 'main@bb9.i'(int,int,array(int),int).
:- mode 'main@bb9.i'(in,in,in,in).
:- pred 'main@verifier.error.split'.
:- pred 'main@bb79.i'(int,int,array(int),int).
:- mode 'main@bb79.i'(in,in,in,in).
:- pred 'main@bb59.i'(int,int,array(int),int).
:- mode 'main@bb59.i'(in,in,in,in).
:- pred 'main@bb39.i'(int,int,array(int),int).
:- mode 'main@bb39.i'(in,in,in,in).
:- pred 'main@bb89.i'(int,array(int),int,int).
:- mode 'main@bb89.i'(in,in,in,in).
:- pred 'main@bb69.i'(int,int,array(int),int).
:- mode 'main@bb69.i'(in,in,in,in).
:- pred 'main@bb19.i'(int,int,array(int),int).
:- mode 'main@bb19.i'(in,in,in,in).
:- pred 'main@bb29.i'(int,int,array(int),int).
:- mode 'main@bb29.i'(in,in,in,in).
:- pred 'main@bb49.i'(int,int,array(int),int).
:- mode 'main@bb49.i'(in,in,in,in).
:- pred 'main@entry'(int).
:- mode 'main@entry'(in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A) :- constr((true)).
'main@bb9.i'(A,B,C,D) :- 'main@entry'(E), 
          constr((and(F=E,and(not(A=<0),and(or(not(G),not(H),I=J),and(or(not(G),not(H),C=I),and(or(not(G),not(H),K=0),and(or(not(G),not(H),B=K),and(or(not(H),and(G,H)),and(L=true,and(H=true,not((D=<0)=L)))))))))))).
'main@bb9.i'(A,B,C,D) :- 'main@bb9.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,42)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb19.i'(A,B,C,D) :- 'main@bb9.i'(A,E,F,D), 
          constr((and(or(not(G),not(H),I=F),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=0),and(or(not(G),not(H),B=J),and(or(not(G),not(H),not(K)),and(or(not(H),and(G,H)),and(H=true,not((D=<E)=K)))))))))).
'main@bb19.i'(A,B,C,D) :- 'main@bb19.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,43)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb29.i'(A,B,C,D) :- 'main@bb19.i'(A,E,F,D), 
          constr((and(or(not(G),not(H),I=F),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=0),and(or(not(G),not(H),B=J),and(or(not(G),not(H),not(K)),and(or(not(H),and(G,H)),and(H=true,not((D=<E)=K)))))))))).
'main@bb29.i'(A,B,C,D) :- 'main@bb29.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,44)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb39.i'(A,B,C,D) :- 'main@bb29.i'(A,E,F,D), 
          constr((and(or(not(G),not(H),I=F),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=0),and(or(not(G),not(H),B=J),and(or(not(G),not(H),not(K)),and(or(not(H),and(G,H)),and(H=true,not((D=<E)=K)))))))))).
'main@bb39.i'(A,B,C,D) :- 'main@bb39.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,45)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb49.i'(A,B,C,D) :- 'main@bb39.i'(A,E,F,D), 
          constr((and(or(not(G),not(H),I=F),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=0),and(or(not(G),not(H),B=J),and(or(not(G),not(H),not(K)),and(or(not(H),and(G,H)),and(H=true,not((D=<E)=K)))))))))).
'main@bb49.i'(A,B,C,D) :- 'main@bb49.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,46)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb59.i'(A,B,C,D) :- 'main@bb49.i'(A,E,F,D), 
          constr((and(or(not(G),not(H),I=F),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=0),and(or(not(G),not(H),B=J),and(or(not(G),not(H),not(K)),and(or(not(H),and(G,H)),and(H=true,not((D=<E)=K)))))))))).
'main@bb59.i'(A,B,C,D) :- 'main@bb59.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,47)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb69.i'(A,B,C,D) :- 'main@bb59.i'(A,E,F,D), 
          constr((and(or(not(G),not(H),I=F),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=0),and(or(not(G),not(H),B=J),and(or(not(G),not(H),not(K)),and(or(not(H),and(G,H)),and(H=true,not((D=<E)=K)))))))))).
'main@bb69.i'(A,B,C,D) :- 'main@bb69.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,48)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb79.i'(A,B,C,D) :- 'main@bb69.i'(A,E,F,D), 
          constr((and(or(not(G),not(H),I=F),and(or(not(G),not(H),C=I),and(or(not(G),not(H),J=0),and(or(not(G),not(H),B=J),and(or(not(G),not(H),not(K)),and(or(not(H),and(G,H)),and(H=true,not((D=<E)=K)))))))))).
'main@bb79.i'(A,B,C,D) :- 'main@bb79.i'(A,E,F,D), 
          constr((and(or(not(G=<0),not(H),A=<0),and(or(not(I),not(H),J),and(or(not(H),not(K),L=M),and(or(not(H),not(K),C=L),and(or(not(H),not(K),N=O),and(or(not(H),not(K),B=N),and(or(not(K),and(H,K)),and(or(not(H),M=store(F,G,49)),and(or(not(H),O=1+E),and(or(not(H),G=A+E),and(or(not(H),not(A=<0)),and(or(not(H),and(H,I)),and(K=true,not((D=<E)=J)))))))))))))))).
'main@bb89.i'(A,B,C,D) :- 'main@bb79.i'(A,E,B,D), 
          constr((and(or(not(F),not(G),H=0),and(or(not(F),not(G),C=H),and(or(not(F),not(G),not(I)),and(or(not(G),and(F,G)),and(G=true,not((D=<E)=I)))))))).
'main@bb89.i'(A,B,C,D) :- 'main@bb89.i'(A,B,E,D), 
          constr((and(or(not(F=<0),not(G),A=<0),and(or(not(G),not(H),I),and(or(not(H),not(J),K=L),and(or(not(H),not(J),C=K),and(or(not(G),I=(M=49)),and(or(not(G),F=A+E),and(or(not(G),M=select(B,F)),and(or(not(G),not(A=<0)),and(or(not(G),and(N,G)),and(or(not(J),and(H,J)),and(or(not(H),L=1+E),and(or(not(H),and(H,G)),and(O=true,and(J=true,not((D=<E)=O))))))))))))))))).
'main@verifier.error.split' :- 'main@bb89.i'(A,B,C,D), 
          constr((and(or(not(E=<0),not(F),A=<0),and(or(not(G),not(H),not(F)),and(or(not(F),H=(I=49)),and(or(not(F),E=A+C),and(or(not(F),I=select(B,E)),and(or(not(F),not(A=<0)),and(or(not(F),and(J,F)),and(or(not(G),and(G,F)),and(or(not(K),and(K,G)),and(or(not(L),and(L,K)),and(M=true,and(L=true,not((D=<C)=M))))))))))))))).
ff :- 'main@verifier.error.split', constr((true)).

