; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int Int Int (Array Int Int) Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B Int) (C (Array Int Int)) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= G 0) (= H (+ 1 A)) (= I 1) (>= J 1) (>= (- B A) 1) (= (select C A) J) (new1 H B A C D E F))
      (new1 A B B C D E F)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C (Array Int Int)) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= G 0) (= H (+ 1 A)) (= I 1) (<= J (- 1)) (>= (- B A) 1) (= (select C A) J) (new1 H B A C D E F))
      (new1 A B B C D E F)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C (Array Int Int)) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) )
    (=>
      (and (= G 0) (= H 0) (= I 0) (= J (+ 1 A)) (= K 1) (>= (- B A) 1) (= (select C A) I) (new1 J B B C D E F))
      (new1 A B B C D E F)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) )
    (=>
      (and (= H (+ 1 A)) (= I 1) (>= (- C B) 1) (>= (- B A) 1) (new1 H B C D E F G))
      (new1 A B C D E F G)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) )
    (=>
      (and (= H (+ 1 A)) (= I 1) (<= (- C B) (- 1)) (>= (- B A) 1) (new1 H B C D E F G))
      (new1 A B C D E F G)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) )
    (=>
      (and (= G 0) (= H 0) (= I 0) (= J 0) (= K 0) (>= C 0) (>= (- A B) 0) (>= (- B C) 1) (= (select D C) K))
      (new1 A B C D E F G)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= H 0) (= I 0) (= J 0) (<= E (- 1)) (>= F 0) (>= (- A B) 0) (>= (- B C) 1) (>= (- C F) 1) (= (select D F) E))
      (new1 A B C D E F G)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= H 0) (= I 0) (= J 0) (>= F 0) (>= E 1) (>= (- A B) 0) (>= (- B C) 1) (>= (- C F) 1) (= (select D F) E))
      (new1 A B C D E F G)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) )
    (=>
      (and (= A 1) (= B 0) (>= C 1) (new1 B C C D E F G))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
