; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new2 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new3 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new4 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new5 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new6 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new7 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new8 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select I N) Q) (= (store J N Q ) R) (new8 A B C D E F G H I R K L M O))
      (new8 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (<= (- L K) (- 1)) (>= M 0) (>= (- N A) 0) (>= (- A M) 1) (= (select B M) L) (= (select I M) K))
      (new8 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= M 0) (>= (- N A) 0) (>= (- A M) 1) (>= (- L K) 1) (= (select B M) L) (= (select I M) K))
      (new8 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select H N) Q) (= (store J N Q ) R) (new7 A B C D E F G H I R K L M O))
      (new7 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= (- N A) 0) (new8 A B C D E F G H I J K L M O))
      (new7 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select G N) Q) (= (store H N Q ) R) (new6 A B C D E F G R I J K L M O))
      (new6 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= (- N A) 0) (new7 A B C D E F G H I J K L M O))
      (new6 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select F N) Q) (= (store G N Q ) R) (new5 A B C D E F R H I J K L M O))
      (new5 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= (- N A) 0) (new6 A B C D E F G H I J K L M O))
      (new5 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select E N) Q) (= (store F N Q ) R) (new4 A B C D E R G H I J K L M O))
      (new4 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= (- N A) 0) (new5 A B C D E F G H I J K L M O))
      (new4 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select D N) Q) (= (store E N Q ) R) (new3 A B C D R F G H I J K L M O))
      (new3 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= (- N A) 0) (new4 A B C D E F G H I J K L M O))
      (new3 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select C N) Q) (= (store D N Q ) R) (new2 A B C R E F G H I J K L M O))
      (new2 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= (- N A) 0) (new3 A B C D E F G H I J K L M O))
      (new2 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R (Array Int Int)) )
    (=>
      (and (= O (+ 1 N)) (= P 1) (>= (- A N) 1) (= (select B N) Q) (= (store C N Q ) R) (new1 A B R D E F G H I J K L M O))
      (new1 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K Int) (L Int) (M Int) (N Int) (O Int) )
    (=>
      (and (= O 0) (>= (- N A) 0) (new2 A B C D E F G H I J K L M O))
      (new1 A B C D E F G H I J K L M N)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I (Array Int Int)) (J (Array Int Int)) (K (Array Int Int)) (L (Array Int Int)) (M Int) (N Int) (O Int) )
    (=>
      (and (= A 1) (= B 0) (>= C 1) (new1 C D E F G H I J K L M N O B))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
