% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,array(int),array(int),array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new1(in,in,in,in,in,in,in,in,in,in,in).
:- pred new2(int,array(int),array(int),array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new2(in,in,in,in,in,in,in,in,in,in,in).
:- pred new3(int,array(int),array(int),array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new3(in,in,in,in,in,in,in,in,in,in,in).
:- pred new4(int,array(int),array(int),array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new4(in,in,in,in,in,in,in,in,in,in,in).
:- pred new5(int,array(int),array(int),array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new5(in,in,in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new5(A,B,C,D,E,F,G,H,I,J,K) :- new5(A,B,C,D,E,F,L,H,I,J,M), 
          constr((and(store(G,K,N)=L,and(select(F,K)=N,and(A-K>=1,and(O=1,M=1+K)))))).
new5(A,B,C,D,E,F,G,H,I,J,K) :- 
          constr((and(select(G,J)=H,and(select(B,J)=I,and(A-J>=1,and(K-A>=0,and(J>=0,and(I-H=< - 1,L=0)))))))).
new5(A,B,C,D,E,F,G,H,I,J,K) :- 
          constr((and(select(G,J)=H,and(select(B,J)=I,and(I-H>=1,and(A-J>=1,and(K-A>=0,and(J>=0,L=0)))))))).
new4(A,B,C,D,E,F,G,H,I,J,K) :- new4(A,B,C,D,E,L,G,H,I,J,M), 
          constr((and(store(F,K,N)=L,and(select(E,K)=N,and(A-K>=1,and(O=1,M=1+K)))))).
new4(A,B,C,D,E,F,G,H,I,J,K) :- new5(A,B,C,D,E,F,G,H,I,J,L), 
          constr((and(K-A>=0,L=0))).
new3(A,B,C,D,E,F,G,H,I,J,K) :- new3(A,B,C,D,L,F,G,H,I,J,M), 
          constr((and(store(E,K,N)=L,and(select(D,K)=N,and(A-K>=1,and(O=1,M=1+K)))))).
new3(A,B,C,D,E,F,G,H,I,J,K) :- new4(A,B,C,D,E,F,G,H,I,J,L), 
          constr((and(K-A>=0,L=0))).
new2(A,B,C,D,E,F,G,H,I,J,K) :- new2(A,B,C,L,E,F,G,H,I,J,M), 
          constr((and(store(D,K,N)=L,and(select(C,K)=N,and(A-K>=1,and(O=1,M=1+K)))))).
new2(A,B,C,D,E,F,G,H,I,J,K) :- new3(A,B,C,D,E,F,G,H,I,J,L), 
          constr((and(K-A>=0,L=0))).
new1(A,B,C,D,E,F,G,H,I,J,K) :- new1(A,B,L,D,E,F,G,H,I,J,M), 
          constr((and(store(C,K,N)=L,and(select(B,K)=N,and(A-K>=1,and(O=1,M=1+K)))))).
new1(A,B,C,D,E,F,G,H,I,J,K) :- new2(A,B,C,D,E,F,G,H,I,J,L), 
          constr((and(K-A>=0,L=0))).
incorrect :- new1(A,B,C,D,E,F,G,H,I,J,K), constr((and(A>=1,and(K=0,L=1)))).

