% Automatically generated by smt2map




:- pred 'main@precall.split'.
:- pred 'main@entry'(array(int)).
:- mode 'main@entry'(in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A) :- constr((true)).
'main@precall.split' :- 'main@entry'(A), 
          constr((B=store(A,C,0))).
ff :- 'main@precall.split', constr((true)).

