% Automatically generated by smt2map




:- pred 'main@entry'(int).
:- mode 'main@entry'(in).
:- pred 'main@orig.main.exit.split'.
:- pred 'main@.lr.ph'(int,int,array(int)).
:- mode 'main@.lr.ph'(in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A) :- constr((true)).
'main@.lr.ph'(A,B,C) :- 'main@entry'(D), 
          constr((and(and(E=store(F,G,H),I=store(E,J,K),L=store(I,M,N),O=store(L,P,Q),R=store(O,S,T),U=store(R,V,W),X=store(U,Y,Z),A1=store(X,B1,C1),D1=store(A1,E1,F1),G1=store(D1,H1,I1),C=store(G1,J1,0),K1=D,G=B,L1=D,J=1+B,M1=D,M=2+B,N1=D,P=3+B,O1=D,S=4+B,P1=D,V=5+B,Q1=D,Y=6+B,R1=D,B1=7+B,S1=D,E1=8+B,T1=D,H1=9+B,J1=10+B,U1= - 48+H,not(B=<0),or(not(V1),not(W1),X1),or(not(W1),not(Y1),Z1=0),or(not(W1),not(Y1),A=Z1),or(not(G=<0),B=<0),or(not(J=<0),B=<0),or(not(M=<0),B=<0),or(not(P=<0),B=<0),or(not(S=<0),B=<0),or(not(V=<0),B=<0),or(not(Y=<0),B=<0),or(not(B1=<0),B=<0),or(not(E1=<0),B=<0),or(not(H1=<0),B=<0),or(not(J1=<0),B=<0),or(not(Y1),and(W1,Y1)),or(not(W1),and(W1,V1)),Y1=true,A2),A2=(X1=and(not(10=<U1),U1>=0))))).
'main@.lr.ph'(A,B,C) :- 'main@.lr.ph'(D,B,C), 
          constr((and(and(E=1+D,F=B+E,G=select(C,F),H= - 48+G,not(B=<0),or(not(I),not(J),K=E),or(not(I),not(J),A=K),or(not(I),not(J),L),or(not(F=<0),B=<0),or(not(J),and(I,J)),J=true,M),M=(L=and(not(10=<H),H>=0))))).
'main@orig.main.exit.split' :- 'main@entry'(A), 
          constr((and(and(B=store(C,D,E),F=store(B,G,H),I=store(F,J,K),L=store(I,M,N),O=store(L,P,Q),R=store(O,S,T),U=store(R,V,W),X=store(U,Y,Z),A1=store(X,B1,C1),D1=store(E1,F1,0),E1=store(A1,G1,H1),I1=A,J1=A,K1=A,L1=A,M1=A,N1=A,O1=A,P1=A,Q1=A,F1=10+R1,S1= - 48+E,D=R1,G=1+R1,J=2+R1,M=3+R1,P=4+R1,S=5+R1,V=6+R1,Y=7+R1,B1=8+R1,T1=A,G1=9+R1,not(R1=<0),or(not(U1),not(V1),not(W1)),or(R1=<0,not(F1=<0)),or(R1=<0,not(D=<0)),or(R1=<0,not(G=<0)),or(R1=<0,not(J=<0)),or(R1=<0,not(M=<0)),or(R1=<0,not(P=<0)),or(R1=<0,not(S=<0)),or(R1=<0,not(V=<0)),or(R1=<0,not(Y=<0)),or(R1=<0,not(B1=<0)),or(not(G1=<0),R1=<0),or(not(W1),and(U1,W1)),or(not(W1),not(X1)),or(not(Y1),and(Y1,W1)),not(W1),Y1=true,Z1),Z1=(V1=and(not(10=<S1),S1>=0))))).
'main@orig.main.exit.split' :- 'main@.lr.ph'(A,B,C), 
          constr((and(and(D=1+A,E=select(C,F),G= - 48+E,F=B+D,not(B=<0),or(not(H),not(I),not(J)),or(not(F=<0),B=<0),or(not(J),and(H,J)),or(not(K),and(K,J)),or(not(K),not(L)),or(not(M),and(M,K)),not(K),M=true,N),N=(I=and(not(10=<G),G>=0))))).
ff :- 'main@orig.main.exit.split', constr((true)).

