; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int Int Int (Array Int Int) Int Int Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R Int) (S Int) (T Int) (U Int) (V Int) (W Int) (X (Array Int Int)) (Y (Array Int Int)) )
    (=>
      (and (= J (- (+ (- 1) C) A)) (= K (- C A)) (= L 1) (= M (+ 1 B)) (= N 1) (= O (+ 1 B)) (= P (+ 1 B)) (= Q (+ 1 B)) (= R (+ 1 B)) (= S 1) (>= (- T U) 1) (>= (- (- C A) B) 2) (= (select D B) T) (= (select D O) U) (= (select D B) V) (= (select D P) W) (= (store D B W ) X) (= (store X Q V ) Y) (new1 A R C Y V F G H M))
      (new1 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R Int) (S Int) )
    (=>
      (and (= J (- (+ (- 1) C) A)) (= K (- C A)) (= L 1) (= M (+ 1 B)) (= N 1) (= O (+ 1 B)) (= P (+ 1 B)) (= Q 1) (<= (- R S) 0) (>= (- (- C A) B) 2) (= (select D B) R) (= (select D O) S) (new1 A P C D E F G H M))
      (new1 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R Int) )
    (=>
      (and (= C (+ (+ 1 A) B)) (= J (+ 1 B)) (= K 1) (= L (+ (+ 1 A) B)) (= M 0) (= N (+ (+ 1 A) B)) (= O (+ 1 B)) (= P 1) (= Q (+ (+ 1 A) B)) (= R 0) (<= (- H B) 0) (>= A 0) (>= H 0) (>= (- G F) 1) (= (select D H) G) (= (select D B) F))
      (new1 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) (E Int) (F Int) (G Int) (H (Array Int Int)) (I Int) (J Int) (K Int) (L Int) (M Int) )
    (=>
      (and (= A 0) (= B 0) (= C (+ 1 D)) (= E 1) (= F 0) (>= D 0) (>= (- G D) 1) (new1 D F G H I J K L M))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
