% Automatically generated by smt2map




:- pred 'main@bb34.i'(int,array(int),int,array(int),int,int,array(int),int,int,int,array(int),array(int)).
:- mode 'main@bb34.i'(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred 'main@verifier.error.split'.
:- pred 'main@entry'(int,int).
:- mode 'main@entry'(in,in).
:- pred 'main@bb17.i'(int,int,int,array(int),int,array(int),int,int,int,int,array(int),array(int),array(int)).
:- mode 'main@bb17.i'(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred 'main@bb48.i'(int,array(int),int,array(int),int,int,array(int),int,int,array(int)).
:- mode 'main@bb48.i'(in,in,in,in,in,in,in,in,in,in).
:- pred 'main@bb62.i'(int,array(int),int,array(int),int,int,array(int),int).
:- mode 'main@bb62.i'(in,in,in,in,in,in,in,in).
:- pred 'main@bb76.i'(int,array(int),int,array(int),int,int).
:- mode 'main@bb76.i'(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A,B) :- constr((true)).
'main@bb17.i'(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 'main@entry'(A,N), 
          constr((~ ((J=<0)=O)&(P=true&(O=true&(and(Q,P)&(not(P)&(C=R&(not(P)&(not(Q)&(R=0&(not(P)&(not(Q)&(F=S&(not(P)&(not(Q)&(D=T&(not(P)&(not(Q)&(T=U&(not(P)&(not(Q)&(S=V&(not(P)&(not(Q)&(~ (I=<0)&(~ (H=<0)&(~ (G=<0)&(~ (E=<0)&(~ (B=<0)&W=N))))))))))))))))))))))))))))).
'main@bb17.i'(A,B,C,D,E,F,G,H,I,J,K,L,M) :- 
          'main@bb17.i'(A,B,N,O,E,P,G,H,I,J,K,L,M), 
          constr((~ ((J=<N)=Q)&(R=true&(and(S,T)&(not(S)&(not(E=<0)&(not(S)&(not(B=<0)&(not(S)&(U=1+N&(not(S)&(V=E+N&(not(S)&(W=B+N&(not(S)&(X=A&(not(S)&(Y=store(O,W,Z)&(not(S)&(A1=store(P,V,Z)&(not(S)&(and(S,R)&(not(R)&(C=B1&(not(R)&(not(S)&(B1=U&(not(R)&(not(S)&(F=C1&(not(R)&(not(S)&(D=D1&(not(R)&(not(S)&(D1=Y&(not(R)&(not(S)&(C1=A1&(not(R)&(not(S)&(Q&(not(S)&(not(T)&(E=<0&(not(S)&(not(V=<0)&(B=<0&(not(S)&not(W=<0)))))))))))))))))))))))))))))))))))))))))))))))))).
'main@bb34.i'(A,B,C,D,E,F,G,H,I,J,K,L) :- 
          'main@bb17.i'(M,A,N,B,C,D,F,H,I,J,K,L,O), 
          constr((~ ((J=<N)=P)&(Q=true&(and(Q,R)&(not(Q)&(not(R)&(not(P)&(not(Q)&(not(R)&(E=S&(not(Q)&(not(R)&(S=0&(not(Q)&(not(R)&(G=T&(not(Q)&(not(R)&(T=O&not(Q)))))))))))))))))))).
'main@bb34.i'(A,B,C,D,E,F,G,H,I,J,K,L) :- 'main@bb34.i'(A,B,C,D,M,F,N,H,I,J,K,L), 
          constr((~ ((J=<M)=O)&(P=true&(and(P,Q)&(not(P)&(and(Q,R)&(not(Q)&(not(C=<0)&(not(Q)&(not(F=<0)&(not(Q)&(S=C+M&(not(Q)&(T=select(D,S)&(not(Q)&(U=1+M&(not(Q)&(V=F+M&(not(Q)&(W=store(N,V,T)&(not(Q)&(not(Q)&(E=X&(not(P)&(not(Q)&(X=U&(not(P)&(not(Q)&(G=Y&(not(P)&(not(Q)&(Y=W&(not(P)&(not(R)&(not(Q)&(O&(not(S=<0)&(not(Q)&(C=<0&(not(Q)&(F=<0&not(V=<0)))))))))))))))))))))))))))))))))))))))))).
'main@bb48.i'(A,B,C,D,E,F,G,H,I,J) :- 'main@bb34.i'(A,B,K,L,M,C,D,F,H,I,J,N), 
          constr((~ ((I=<M)=O)&(P=true&(and(Q,P)&(not(P)&(not(Q)&(not(P)&(not(O)&(E=R&(not(P)&(not(Q)&(R=0&(not(P)&(not(Q)&(G=S&(not(P)&(not(Q)&(S=N&(not(P)&not(Q)))))))))))))))))))).
'main@bb48.i'(A,B,C,D,E,F,G,H,I,J) :- 'main@bb48.i'(A,B,C,D,K,F,L,H,I,J), 
          constr((~ ((I=<K)=M)&(N=true&(and(O,P)&(not(O)&(not(C=<0)&(not(O)&(not(F=<0)&(not(O)&(Q=F+K&(not(O)&(R=C+K&(not(O)&(S=1+K&(not(O)&(T=select(D,R)&(not(O)&(U=store(L,Q,T)&(not(O)&(and(O,N)&(not(N)&(E=V&(not(N)&(not(O)&(V=S&(not(N)&(not(O)&(G=W&(not(N)&(not(O)&(W=U&(not(N)&(not(O)&(not(P)&(not(O)&(M&(not(O)&(C=<0&(not(R=<0)&(not(Q=<0)&(not(O)&F=<0))))))))))))))))))))))))))))))))))))))))).
'main@bb62.i'(A,B,C,D,E,F,G,H) :- 'main@bb48.i'(A,B,I,J,K,C,D,F,H,L), 
          constr((~ ((H=<K)=M)&(N=true&(and(O,N)&(not(N)&(not(N)&(not(O)&(not(M)&(E=P&(not(N)&(not(O)&(P=0&(not(N)&(not(O)&(G=Q&(not(N)&(not(O)&(Q=L&(not(N)&not(O)))))))))))))))))))).
'main@bb62.i'(A,B,C,D,E,F,G,H) :- 'main@bb62.i'(A,B,C,D,I,F,J,H), 
          constr((~ ((H=<I)=K)&(L=true&(and(M,N)&(not(M)&(not(F=<0)&(not(M)&(not(C=<0)&(not(M)&(O=1+I&(not(M)&(P=C+I&(not(M)&(Q=F+I&(not(M)&(R=select(D,P)&(not(M)&(S=store(J,Q,R)&(not(M)&(and(M,L)&(not(L)&(K&(not(N)&(not(M)&(E=T&(not(L)&(not(M)&(T=O&(not(L)&(not(M)&(G=U&(not(L)&(not(M)&(U=S&(not(L)&(not(M)&(not(Q=<0)&(F=<0&(not(M)&(not(P=<0)&(C=<0&not(M)))))))))))))))))))))))))))))))))))))))))).
'main@bb76.i'(A,B,C,D,E,F) :- 'main@bb62.i'(A,B,G,H,I,C,D,F), 
          constr((~ ((F=<I)=J)&(K=true&(and(L,K)&(not(K)&(not(L)&(not(K)&(not(J)&(E=M&(not(K)&(not(L)&(M=0&(not(K)&not(L)))))))))))))).
'main@bb76.i'(A,B,C,D,E,F) :- 'main@bb76.i'(A,B,C,D,G,F), 
          constr((~ ((F=<G)=H)&(I=true&(H=true&(and(J,K)&(not(K)&(not(C=<0)&(not(K)&(not(A=<0)&(not(K)&(L=select(D,M)&(not(K)&(N=A+G&(not(K)&(O=select(B,N)&(not(K)&(M=C+G&(not(K)&(P=(O=L)&(not(K)&(and(K,Q)&(not(Q)&(R=1+G&(not(Q)&(and(Q,I)&(not(I)&(not(Q)&(not(K)&(P&(not(M=<0)&(not(K)&(C=<0&(not(N=<0)&(not(K)&(A=<0&(E=S&(not(I)&(not(Q)&(S=R&(not(I)&not(Q))))))))))))))))))))))))))))))))))))))))).
'main@verifier.error.split' :- 'main@bb76.i'(A,B,C,D,E,F), 
          constr((~ ((F=<E)=G)&(G=true&(H=true&(and(H,I)&(not(H)&(and(I,J)&(not(I)&(and(J,K)&(not(J)&(and(L,K)&(not(K)&(not(C=<0)&(not(K)&(not(A=<0)&(not(K)&(M=C+E&(not(K)&(N=select(D,M)&(not(K)&(O=select(B,P)&(not(K)&(P=A+E&(not(K)&(Q=(O=N)&(not(K)&(not(K)&(not(Q)&(not(J)&(not(K)&(not(M=<0)&(C=<0&(A=<0&(not(P=<0)&not(K))))))))))))))))))))))))))))))))))).
ff :- 'main@verifier.error.split', constr((true)).

