% Automatically generated by smt2map




:- pred chc_comp_false.
:- pred inv_main_42(int,int,int,array(int),int,int,int,array(int)).
:- mode inv_main_42(in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_42(A,B,C,D,E,F,G,H) :- 
          constr((D=H&(C=I&(A=E&(J=G&(~ (J=0)&(~ (G=0)&(B= - 1+J&(F=1+I&(~ (select(D,C)=A)& ~ (select(H,I)=E))))))))))).
inv_main_42(A,B,C,D,E,F,G,H) :- inv_main_42(A,I,J,D,E,K,L,H), 
          constr((M=not(select(D,1+J)=A)&(not(select(H,K)=E)&(not(I=0)&(not(L=1)&(B= - 1+I&(C=1+J&(F=1+K&(G= - 1+L&M))))))))).
inv_main_42(A,B,C,D,E,F,G,H) :- inv_main_42(A,I,J,D,E,F,G,H), 
          constr((K=not(select(D,1+J)=A)&(K&(or(G=1,select(H,F)=E)&(not(I=0)&(B= - 1+I&C=1+J)))))).
inv_main_42(A,B,C,D,E,F,G,H) :- inv_main_42(A,B,C,D,E,I,J,H), 
          constr((K=or(B=0,select(D,1+C)=A)&(not(select(H,I)=E)&(K&(not(J=1)&(F=1+I&G= - 1+J)))))).
chc_comp_false :- 
          constr((A=B&(C=D&(E=F&(G=H&(~ (G=0)&(~ (H=0)&(select(A,C)=E& ~ (select(B,D)=F))))))))).
chc_comp_false :- 
          constr((A=B&(C=D&(E=F&(G=H&(G=0&(~ (H=0)& ~ (select(B,D)=F)))))))).
chc_comp_false :- 
          constr((A=B&(C=D&(E=F&(G=H&(~ (G=0)&(~ (H=0)&(~ (select(A,C)=E)&select(B,D)=F)))))))).
chc_comp_false :- 
          constr((A=B&(C=D&(E=F&(G=H&(~ (G=0)&(H=0& ~ (select(A,C)=E)))))))).
chc_comp_false :- 
          constr((A=B&(not(A=B)&(not(C=D)&(C=D&(E=F&(G=H&(~ (G=0)&(~ (H=0)&(select(A,C)=E&select(B,D)=F)))))))))).
chc_comp_false :- 
          constr((A=B&(not(A=B)&(not(C=0)&(C=D&(E=F&(G=H&(~ (G=0)&(H=0&select(A,C)=E))))))))).
chc_comp_false :- 
          constr((A=B&(not(0=C)&(not(A=B)&(D=C&(E=F&(G=H&(G=0&(~ (H=0)&select(B,C)=F))))))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H), 
          constr((I=or(not(D=H),not(C= - 1+F))&(select(H,F)=E&(I&(not(B=0)&(not(G=1)&select(D,1+C)=A)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H), 
          constr((select(D,1+C)=A&(not(C= - 1)&(not(D=H)&(~ (B=0)&G=1))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H), 
          constr((select(H,F)=E&(not(0=F)&(not(D=H)&(B=0& ~ (G=1)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H), constr((~ (D=H)&(B=0&G=1))).
ff :- chc_comp_false, constr((true)).

