% Automatically generated by smt2map




:- pred new9(int,int,int,int).
:- mode new9(in,in,in,in).
:- pred new4(int,int,int).
:- mode new4(in,in,in).
:- pred new8(int,int,int).
:- mode new8(in,in,in).
:- pred new7(int,int,int,int).
:- mode new7(in,in,in,in).
:- pred new6(int,int,int).
:- mode new6(in,in,in).
:- pred new5(int,int,int).
:- mode new5(in,in,in).
:- pred new2(int,int,int).
:- mode new2(in,in,in).
:- pred new3(int,int,int).
:- mode new3(in,in,in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new9(A,B,C,D) :- constr((and(E=0,and(F=0,A=0)))).
new9(A,B,C,D) :- new4(B,C,E), constr((and(A>=1,and(F=1,and(E=1+D,G=0))))).
new9(A,B,C,D) :- new4(B,C,E), constr((and(A=< - 1,and(F=1,and(E=1+D,G=0))))).
new8(A,B,C) :- new9(D,A,B,C), 
          constr((and(B>=0,and(E=1,and(F= - 1+A,and(G= - 1-B+A,D=1)))))).
new8(A,B,C) :- new9(D,A,B,C), 
          constr((and(B=< - 1,and(E=1,and(F= - 1+A,and(G= - 1-B+A,D=0)))))).
new7(A,B,C,D) :- constr((and(E=0,and(F=0,A=0)))).
new7(A,B,C,D) :- new8(B,C,D), constr((and(A>=1,E=0))).
new7(A,B,C,D) :- new8(B,C,D), constr((and(A=< - 1,E=0))).
new6(A,B,C) :- new7(D,A,B,C), 
          constr((and(B-A=< - 1,and(E=1,and(F= - 1+A,and(G= - 1-B+A,and(H=0,D=1))))))).
new6(A,B,C) :- new7(D,A,B,C), 
          constr((and(B-A>=0,and(E=1,and(F= - 1+A,and(G= - 1-B+A,and(H=0,D=0))))))).
new5(A,B,C) :- new6(A,B,C), constr((and(C=<7,D=8))).
new5(A,B,C) :- new2(A,D,C), constr((and(C>=8,and(E=1,and(D=1+B,F=8))))).
new4(A,B,C) :- new5(A,B,C), constr((true)).
new3(A,B,C) :- new4(A,B,D), constr((and(B-A=< - 1,D=0))).
new2(A,B,C) :- new3(A,B,C), constr((true)).
new1 :- new2(A,B,C), constr((B=0)).
incorrect :- new1, constr((true)).

