% Automatically generated by smt2map




:- pred new16(int,int,int,int,int).
:- mode new16(in,in,in,in,in).
:- pred new6(int,int,int,int,int).
:- mode new6(in,in,in,in,in).
:- pred new15(int,int,int,int,int,int).
:- mode new15(in,in,in,in,in,in).
:- pred new14(int,int,int,int,int).
:- mode new14(in,in,in,in,in).
:- pred new13(int,int,int,int,int,int).
:- mode new13(in,in,in,in,in,in).
:- pred new12(int,int,int,int,int).
:- mode new12(in,in,in,in,in).
:- pred new11(int,int,int,int,int,int).
:- mode new11(in,in,in,in,in,in).
:- pred new10(int,int,int,int,int).
:- mode new10(in,in,in,in,in).
:- pred new9(int,int,int,int,int,int).
:- mode new9(in,in,in,in,in,in).
:- pred new8(int,int,int,int,int).
:- mode new8(in,in,in,in,in).
:- pred new7(int,int,int,int,int).
:- mode new7(in,in,in,in,in).
:- pred new5(int,int,int,int,int).
:- mode new5(in,in,in,in,in).
:- pred new4(int,int,int,int,int,int).
:- mode new4(in,in,in,in,in,in).
:- pred new3(int,int,int,int,int).
:- mode new3(in,in,in,in,in).
:- pred new2(int,int,int,int,int).
:- mode new2(in,in,in,in,in).
:- pred new1(int,int).
:- mode new1(in,in).
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new16(A,B,C,D,E) :- new6(A,B,F,G,H), 
          constr((and(I=1,and(H= - 1+E,and(J=1,and(G=1+D,and(K=1,and(F=1+C,and(L=0,and(M=0,B=0)))))))))).
new15(A,B,C,D,E,F) :- constr((and(G=0,and(H=0,C=0)))).
new15(A,B,C,D,E,F) :- new16(A,B,D,E,F), constr((and(C>=1,G=0))).
new15(A,B,C,D,E,F) :- new16(A,B,D,E,F), constr((and(C=< - 1,G=0))).
new14(A,B,C,D,E) :- new15(A,B,F,C,D,E), constr((and(C-A=< - 1,F=1))).
new14(A,B,C,D,E) :- new15(A,B,F,C,D,E), constr((and(C-A>=0,F=0))).
new13(A,B,C,D,E,F) :- constr((and(G=0,and(H=0,C=0)))).
new13(A,B,C,D,E,F) :- new14(A,B,D,E,F), constr((and(C>=1,G=0))).
new13(A,B,C,D,E,F) :- new14(A,B,D,E,F), constr((and(C=< - 1,G=0))).
new12(A,B,C,D,E) :- new13(A,B,F,C,D,E), constr((and(C>=0,and(G=0,F=1)))).
new12(A,B,C,D,E) :- new13(A,B,F,C,D,E), constr((and(C=< - 1,and(G=0,F=0)))).
new11(A,B,C,D,E,F) :- constr((and(G=0,and(H=0,C=0)))).
new11(A,B,C,D,E,F) :- new12(A,B,D,E,F), constr((and(C>=1,G=0))).
new11(A,B,C,D,E,F) :- new12(A,B,D,E,F), constr((and(C=< - 1,G=0))).
new10(A,B,C,D,E) :- new11(A,B,F,C,D,E), constr((and(D-A=< - 1,F=1))).
new10(A,B,C,D,E) :- new11(A,B,F,C,D,E), constr((and(D-A>=0,F=0))).
new9(A,B,C,D,E,F) :- constr((and(G=0,and(H=0,C=0)))).
new9(A,B,C,D,E,F) :- new10(A,B,D,E,F), constr((and(C>=1,G=0))).
new9(A,B,C,D,E,F) :- new10(A,B,D,E,F), constr((and(C=< - 1,G=0))).
new8(A,B,C,D,E) :- new9(A,B,F,C,D,E), constr((and(D>=0,and(G=0,F=1)))).
new8(A,B,C,D,E) :- new9(A,B,F,C,D,E), constr((and(D=< - 1,and(G=0,F=0)))).
new7(A,B,C,D,E) :- new8(A,B,C,D,E), constr((and(E>=1,F=0))).
new7(A,B,C,D,E) :- new8(A,B,C,D,E), constr((and(E=< - 1,F=0))).
new6(A,B,C,D,E) :- new7(A,B,C,D,E), constr((true)).
new5(A,B,C,D,E) :- new6(A,B,F,G,E), constr((and(E>=1,and(G=0,and(F=0,H=0))))).
new5(A,B,C,D,E) :- new6(A,B,F,G,E), 
          constr((and(E=< - 1,and(G=0,and(F=0,H=0))))).
new4(A,B,C,D,E,F) :- constr((and(G=0,and(H=0,C=0)))).
new4(A,B,C,D,E,F) :- new5(A,B,D,E,F), constr((and(C>=1,G=0))).
new4(A,B,C,D,E,F) :- new5(A,B,D,E,F), constr((and(C=< - 1,G=0))).
new3(A,B,C,D,E) :- new4(A,B,F,C,D,E), 
          constr((and(A>=1,and(G=1,and(H= - 1+A,and(I=0,F=1)))))).
new3(A,B,C,D,E) :- new4(A,B,F,C,D,E), 
          constr((and(A=<0,and(G=1,and(H= - 1+A,and(I=0,F=0)))))).
new2(A,B,C,D,E) :- new3(A,B,C,D,E), constr((and(A>=1,F=0))).
new1(A,B) :- new2(A,B,C,D,A), constr((true)).
incorrect :- new1(A,B), constr((and(B=0,A=0))).

