% Automatically generated by smt2map




:- pred new18(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new18(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new7(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new7(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new17(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new17(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new16(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new16(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new4(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new4(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new15(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new15(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new14(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new14(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new13(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new13(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new12(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new12(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new11(int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new11(in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new10(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new10(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new9(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new9(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new8(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new8(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new6(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new6(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new5(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new5(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new2(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new2(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new3(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new3(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new1(int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new1(in,in,in,in,in,in,in,in,in,in,in,in).
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new18(A,B,C,D,E,F,G,H,I,J,K,L) :- new7(A,M,C,D,N,F,G,H,I,J,K,L), 
          constr((and(A>=1,and(O=1,and(N=1+E,and(P=1,and(M=1+B,Q=0))))))).
new18(A,B,C,D,E,F,G,H,I,J,K,L) :- new7(A,M,C,D,N,F,G,H,I,J,K,L), 
          constr((and(A=< - 1,and(O=1,and(N=1+E,and(P=1,and(M=1+B,Q=0))))))).
new18(A,B,C,D,E,F,G,H,I,J,K,L) :- new7(A,B,C,D,M,F,G,H,N,J,K,L), 
          constr((and(O=1,and(M=1+E,and(P=1,and(N=1+I,and(Q=0,and(R=0,A=0)))))))).
new17(A,B,C,D,E,F,G,H,I,J,K,L) :- new16(A,B,C,D,M,F,G,H,I,J,K,L), 
          constr((and(H-E>=1,and(N=1,M=1+E)))).
new17(A,B,C,D,E,F,G,H,I,J,K,L) :- new4(A,B,C,D,E,F,G,H,I,J,K,M), 
          constr((and(E-H>=0,and(N=2,and(O=2*J,M=L+2*J))))).
new16(A,B,C,D,E,F,G,H,I,J,K,L) :- new17(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((true)).
new15(A,B,C,D,E,F,G,H,I,J,K,L) :- new14(A,B,C,D,M,F,G,H,N,J,K,L), 
          constr((and(H-I>=1,and(O=1,and(M=1+E,and(P=1,N=1+I)))))).
new15(A,B,C,D,E,F,G,H,I,J,K,L) :- new16(A,B,C,D,F,F,G,H,I,J,K,L), 
          constr((I-H>=0)).
new14(A,B,C,D,E,F,G,H,I,J,K,L) :- new15(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((true)).
new13(A,B,C,D,E,F,G,H,I,J,K,L) :- new12(A,M,C,D,N,F,G,H,I,J,K,L), 
          constr((and(G-B>=1,and(O=1,and(N=1+E,and(P=1,M=1+B)))))).
new13(A,B,C,D,E,F,G,H,I,J,K,L) :- new14(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((B-G>=0)).
new12(A,B,C,D,E,F,G,H,I,J,K,L) :- new13(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((true)).
new11(A,B,C,D,E,F,G,H,I,J,K,L,M) :- constr((and(N=0,and(O=0,M=0)))).
new11(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new12(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((and(M>=1,N=0))).
new11(A,B,C,D,E,F,G,H,I,J,K,L,M) :- new12(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((and(M=< - 1,N=0))).
new10(A,B,C,D,E,F,G,H,I,J,K,L) :- new11(A,B,C,D,E,F,G,H,I,J,K,L,M), 
          constr((and(E-C=<0,M=1))).
new10(A,B,C,D,E,F,G,H,I,J,K,L) :- new11(A,B,C,D,E,F,G,H,I,J,K,L,M), 
          constr((and(E-C>=1,M=0))).
new9(A,B,C,D,E,F,G,H,I,J,K,L) :- new18(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((I-H=< - 1)).
new9(A,B,C,D,E,F,G,H,I,J,K,L) :- new10(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((I-H>=0)).
new8(A,B,C,D,E,F,G,H,I,J,K,L) :- new9(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((B-G=< - 1)).
new8(A,B,C,D,E,F,G,H,I,J,K,L) :- new10(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((B-G>=0)).
new7(A,B,C,D,E,F,G,H,I,J,K,L) :- new8(A,B,C,D,E,F,G,H,I,J,K,L), constr((true)).
new6(A,B,C,D,E,F,G,H,I,J,K,L) :- new7(A,L,C,D,L,L,M,N,M,J,N,L), 
          constr((and(K-N>=0,and(O=M-L,and(P=1,and(Q= - 1+N,and(R= - 1+N,and(J=M-L,C= - 1+N)))))))).
new6(A,B,C,D,E,F,G,H,I,J,K,L) :- new7(A,L,C,D,L,L,M,K,M,J,K,L), 
          constr((and(C-K>=0,and(N=M-L,J=M-L)))).
new5(A,B,C,D,E,F,G,H,I,J,K,L) :- new6(A,B,C,D,E,F,G,H,I,J,M,L), 
          constr((and(C-L-J>=0,and(N=2,and(O=2*J,and(M=L+2*J,P=L+J)))))).
new5(A,B,C,D,E,F,G,H,I,J,K,L) :- new2(A,B,C,D,E,F,G,H,I,M,K,L), 
          constr((and(C-L-J=< - 1,and(N=2,and(M=2*J,O=L+J))))).
new4(A,B,C,D,E,F,G,H,I,J,K,L) :- new5(A,B,C,D,E,F,G,H,I,J,K,L), constr((true)).
new3(A,B,C,D,E,F,G,H,I,J,K,L) :- new4(A,B,C,D,E,F,G,H,I,J,K,M), 
          constr((and(J-C=< - 1,M=1))).
new2(A,B,C,D,E,F,G,H,I,J,K,L) :- new3(A,B,C,D,E,F,G,H,I,J,K,L), constr((true)).
new1(A,B,C,D,E,F,G,H,I,J,K,L) :- new2(A,B,C,D,E,F,G,H,I,M,K,L), constr((M=1)).
incorrect :- new1(A,B,C,D,E,F,G,H,I,J,K,L), 
          constr((and(L=0,and(K=0,and(J=0,and(I=0,and(H=0,and(G=0,and(F=0,and(E=0,and(D=0,and(C=0,and(B=0,A=0))))))))))))).

