% Automatically generated by smt2map




:- pred new6(int,int,int,int,int).
:- mode new6(in,in,in,in,in).
:- pred new5(int,int,int,int).
:- mode new5(in,in,in,in).
:- pred new4(int,int,int,int).
:- mode new4(in,in,in,in).
:- pred new3(int,int,int,int).
:- mode new3(in,in,in,in).
:- pred new2(int,int,int,int).
:- mode new2(in,in,in,in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new6(A,B,C,D,E) :- constr((and(F=0,and(G=0,A=0)))).
new5(A,B,C,D) :- new6(E,A,B,C,D), constr((and(F=17,and(G=17,and(E=1,D=17))))).
new5(A,B,C,D) :- new6(E,A,B,C,D), constr((and(D>=18,and(F=17,E=0)))).
new5(A,B,C,D) :- new6(E,A,B,C,D), constr((and(D=<16,and(F=17,E=0)))).
new4(A,B,C,D) :- new5(A,B,C,E), 
          constr((and(F=1,and(G= - 1+E,and(H=3,and(I= - 4+E,and(J= - 1+E,C= - 4+E))))))).
new3(A,B,C,D) :- new4(A,B,E,D), 
          constr((and(F=1,and(G= - 1+E,and(H=2,and(I= - 3+E,and(J= - 1+E,B= - 3+E))))))).
new2(A,B,C,D) :- new3(A,E,C,D), 
          constr((and(F=1,and(G= - 1+E,and(H=1,and(I= - 2+E,and(J= - 1+E,A= - 2+E))))))).
new1 :- new2(A,B,C,D), constr((A=8)).
incorrect :- new1, constr((true)).

