% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,int,array(int),int,int,int,int,int).
:- mode new1(in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new1(A,B,C,D,E,F,G,H) :- new1(I,B,J,D,E,F,G,K), 
          constr((store(C,A,L)=J&(select(C,M)=N&(B-A>=1&(O=1&(I=1+A&(M= - 1+A&(P=1&(L=1+N&(Q=1&K= - 1+A)))))))))).
new1(A,B,C,D,E,F,G,H) :- 
          constr((select(C,F)=D&(select(C,I)=E&(B-F>=2&(A-B>=0&(F>=0&(E-D=<0&(J=1&(I=1+F&(K=1+F&(L=1+D&(M=1&(N=1+F&(O=1+F&(P=1+F&(Q=1&G=1+F)))))))))))))))).
new1(A,B,C,D,E,F,G,H) :- 
          constr((select(C,F)=D&(select(C,I)=E&(E-D>=2&(B-F>=2&(A-B>=0&(F>=0&(J=1&(I=1+F&(K=1+F&(L=1+D&(M=1&(N=1+F&(O=1+F&(P=1+F&(Q=1&G=1+F)))))))))))))))).
incorrect :- new1(A,B,C,D,E,F,G,H), 
          constr((store(I,J,K)=C&(B>=1&(A=1&(J=0&(K=7&L=1)))))).

