% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,int,int,array(int),int,int,int).
:- mode new1(in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new1(A,B,B,C,D,E,F) :- new1(G,B,A,C,D,E,F), 
          constr((select(C,A)=H&(B-A>=1&(H>=1&(I=1&(G=1+A&J=0)))))).
new1(A,B,B,C,D,E,F) :- new1(G,B,A,C,D,E,F), 
          constr((select(C,A)=H&(B-A>=1&(H=< - 1&(I=1&(G=1+A&J=0)))))).
new1(A,B,B,C,D,E,F) :- new1(G,B,B,C,D,E,F), 
          constr((select(C,A)=H&(B-A>=1&(I=1&(G=1+A&(H=0&(J=0&K=0))))))).
new1(A,B,C,D,E,F,G) :- new1(H,B,C,D,E,F,G), 
          constr((B-A>=1&(C-B>=1&(I=1&H=1+A)))).
new1(A,B,C,D,E,F,G) :- new1(H,B,C,D,E,F,G), 
          constr((B-A>=1&(C-B=< - 1&(I=1&H=1+A)))).
new1(A,B,C,D,E,F,G) :- 
          constr((select(D,C)=H&(B-C>=1&(A-B>=0&(C>=0&(H=0&(I=0&(J=0&(K=0&G=0))))))))).
new1(A,B,C,D,E,F,G) :- 
          constr((select(D,F)=E&(C-F>=1&(B-C>=1&(A-B>=0&(F>=0&(E=< - 1&(H=0&(I=0&J=0))))))))).
new1(A,B,C,D,E,F,G) :- 
          constr((select(D,F)=E&(C-F>=1&(B-C>=1&(A-B>=0&(E>=1&(F>=0&(H=0&(I=0&J=0))))))))).
incorrect :- new1(A,B,B,C,D,E,F), constr((B>=1&(A=0&G=1))).

