% Automatically generated by smt2map




:- pred new48(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new48(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new6(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new6(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new47(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new47(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new46(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new46(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new45(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new45(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new44(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new44(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new43(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new43(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new42(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new42(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new41(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new41(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new40(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new40(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new39(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new39(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new38(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new38(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new37(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new37(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new36(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new36(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new35(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new35(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new34(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new34(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new33(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new33(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new32(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new32(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new31(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new31(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new30(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new30(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new29(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new29(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new28(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new28(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new27(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new27(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new26(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new26(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new25(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new25(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new24(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new24(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new23(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new23(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new22(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new22(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new21(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new21(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new20(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new20(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new19(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new19(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new18(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new18(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new17(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new17(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new16(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new16(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new15(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new15(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new14(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new14(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new13(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new13(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new12(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new12(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new11(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new11(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new10(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new10(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new9(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new9(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new8(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new8(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new7(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new7(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new5(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new5(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new4(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new4(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new3(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new3(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new2(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int).
:- mode new2(in,in,in,in,in,in,in,in,in,in,in,in,in,in,in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new48(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new6(P,Q,C,D,E,F,R,H,I,J,K,L,M,N,O), 
          constr((and(G>=1,and(S=1,and(R= - 1+G,and(T=1,and(Q=1+B,and(U=1,and(P= - 1+A,V=1))))))))).
new47(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new6(A,B,P,Q,E,R,G,H,I,J,K,L,M,N,O), 
          constr((and(F>=1,and(S=1,and(R= - 1+F,and(T=1,and(Q=1+D,and(U=1,and(P= - 1+C,V=1))))))))).
new46(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new6(A,B,C,D,P,Q,G,H,I,J,K,L,M,N,O), 
          constr((and(E>=1,and(R=1,and(Q=1+F,and(S=1,and(P= - 1+E,T=1))))))).
new45(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new6(A,B,C,P,Q,F,R,H,I,J,K,L,M,N,O), 
          constr((and(D>=1,and(S=1,and(R=1+G,and(T=1,and(Q=1+E,and(U=1,and(P= - 1+D,V=1))))))))).
new44(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new45(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(J>=1,P=0))).
new44(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new45(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(J=< - 1,P=0))).
new44(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new46(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(P=0,and(Q=0,J=0)))).
new43(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new44(A,B,C,D,E,F,G,H,I,P,K,L,M,N,O), 
          constr((true)).
new42(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new47(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(C>=1,P=1))).
new41(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new42(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(K>=1,P=0))).
new41(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new42(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(K=< - 1,P=0))).
new41(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new43(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(P=0,and(Q=0,K=0)))).
new40(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new41(A,B,C,D,E,F,G,H,I,J,P,L,M,N,O), 
          constr((true)).
new39(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new6(A,P,Q,D,E,R,G,H,I,J,K,L,M,N,O), 
          constr((and(B>=1,and(S=1,and(R=1+F,and(T=1,and(Q=1+C,and(U=1,and(P= - 1+B,V=1))))))))).
new38(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new39(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(L>=1,P=0))).
new38(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new39(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(L=< - 1,P=0))).
new38(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new40(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(P=0,and(Q=0,L=0)))).
new37(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new38(A,B,C,D,E,F,G,H,I,J,K,P,M,N,O), 
          constr((true)).
new36(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new48(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(A>=1,P=1))).
new35(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new36(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(M>=1,P=0))).
new35(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new36(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(M=< - 1,P=0))).
new35(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new37(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(P=0,and(Q=0,M=0)))).
new34(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new35(A,B,C,D,E,F,G,H,I,J,K,L,P,N,O), 
          constr((true)).
new33(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new6(P,B,C,D,E,Q,G,H,I,J,K,L,M,N,O), 
          constr((and(F>=1,and(R=1,and(Q= - 1+F,and(S=1,and(P=1+A,T=1))))))).
new32(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new33(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(N>=1,P=0))).
new32(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new33(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(N=< - 1,P=0))).
new32(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new34(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(P=0,and(Q=0,N=0)))).
new31(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new30(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new31(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(F+E+D+A+B>=1,and(Q=A+B,and(R=D+A+B,and(S=E+D+A+B,and(T=1,and(U=F+E+D+A+B,P=1)))))))).
new30(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new31(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(F+E+D+A+B=<0,and(Q=A+B,and(R=D+A+B,and(S=E+D+A+B,and(T=1,and(U=F+E+D+A+B,P=0)))))))).
new29(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new29(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new30(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new29(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new30(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new28(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new29(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(G+D+B+C>=1,and(Q=B+C,and(R=D+B+C,and(S=1,and(T=G+D+B+C,P=1))))))).
new28(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new29(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(G+D+B+C=<0,and(Q=B+C,and(R=D+B+C,and(S=1,and(T=G+D+B+C,P=0))))))).
new27(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new27(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new28(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new27(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new28(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new26(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new27(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(A>=0,and(Q=0,P=1)))).
new26(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new27(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(A=< - 1,and(Q=0,P=0)))).
new25(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new25(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new26(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new25(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new26(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new24(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new25(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(B>=0,and(Q=0,P=1)))).
new24(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new25(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(B=< - 1,and(Q=0,P=0)))).
new23(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new23(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new24(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new23(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new24(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new22(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new23(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(C>=0,and(Q=0,P=1)))).
new22(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new23(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(C=< - 1,and(Q=0,P=0)))).
new21(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new21(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new22(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new21(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new22(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new20(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new21(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(D>=0,and(Q=0,P=1)))).
new20(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new21(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(D=< - 1,and(Q=0,P=0)))).
new19(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new19(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new20(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new19(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new20(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new18(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new19(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(E>=0,and(Q=0,P=1)))).
new18(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new19(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(E=< - 1,and(Q=0,P=0)))).
new17(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new17(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new18(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new17(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new18(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new16(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new17(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(F>=0,and(Q=0,P=1)))).
new16(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new17(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(F=< - 1,and(Q=0,P=0)))).
new15(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new15(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new16(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new15(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new16(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new14(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new15(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(G>=0,and(Q=0,P=1)))).
new14(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new15(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(G=< - 1,and(Q=0,P=0)))).
new13(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new13(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new14(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new13(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new14(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new12(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new13(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(Q=A+B,and(R=D+A+B,and(S=E+D+A+B,and(T=F+E+D+A+B,and(U=F+E+D+A+B,and(P=1,H=F+E+D+A+B)))))))).
new12(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new13(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(H-F-E-D-A-B=< - 1,and(Q=A+B,and(R=D+A+B,and(S=E+D+A+B,and(T=F+E+D+A+B,P=0))))))).
new12(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new13(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(H-F-E-D-A-B>=1,and(Q=A+B,and(R=D+A+B,and(S=E+D+A+B,and(T=F+E+D+A+B,P=0))))))).
new11(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- constr((and(Q=0,and(R=0,A=0)))).
new11(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new12(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A>=1,Q=0))).
new11(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) :- new12(B,C,D,E,F,G,H,I,J,K,L,M,N,O,P), 
          constr((and(A=< - 1,Q=0))).
new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new11(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(Q=B+C,and(R=D+B+C,and(S=G+D+B+C,and(T=G+D+B+C,and(P=1,I=G+D+B+C))))))).
new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new11(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(I-G-D-B-C=< - 1,and(Q=B+C,and(R=D+B+C,and(S=G+D+B+C,P=0)))))).
new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new11(P,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(I-G-D-B-C>=1,and(Q=B+C,and(R=D+B+C,and(S=G+D+B+C,P=0)))))).
new9(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new32(A,B,C,D,E,F,G,H,I,J,K,L,M,P,O), 
          constr((true)).
new8(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new9(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(O>=1,P=0))).
new8(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new9(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(O=< - 1,P=0))).
new8(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new10(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(P=0,and(Q=0,O=0)))).
new7(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new8(A,B,C,D,E,F,G,H,I,J,K,L,M,N,P), 
          constr((true)).
new6(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new7(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((true)).
new5(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new6(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(I>=1,P=1))).
new4(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) :- new5(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(H>=1,P=1))).
new3(A,B,C,D,E,F,G,H,G,I,J,K,L,M,N) :- new4(A,B,C,D,E,F,G,H,G,I,J,K,L,M,N), 
          constr((true)).
new2(A,B,C,D,E,F,G,F,H,I,J,K,L,M,N) :- new3(A,B,C,D,E,F,G,F,H,I,J,K,L,M,N), 
          constr((true)).
new1 :- new2(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O), 
          constr((and(E=0,and(D=0,and(C=0,and(B=0,A=0)))))).
incorrect :- new1, constr((true)).

