; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int Int Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R Int) (S Int) (T (Array Int Int)) )
    (=>
      (and (= M 0) (= N (+ 1 F)) (= O 1) (= P (+ 1 E)) (= Q 1) (>= R 0) (>= (- A E) 1) (= (select B E) R) (= (select B E) S) (= (store C F S ) T) (new1 A B T D P N G H I J K L))
      (new1 A B C D E F G H I J K L)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) (O Int) (P Int) (Q Int) (R Int) (S Int) (T (Array Int Int)) )
    (=>
      (and (= M 0) (= N (+ 1 G)) (= O 1) (= P (+ 1 E)) (= Q 1) (<= R (- 1)) (>= (- A E) 1) (= (select B E) R) (= (select B E) S) (= (store D G S ) T) (new1 A B C T P F N H I J K L))
      (new1 A B C D E F G H I J K L)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) )
    (=>
      (and (= M 0) (= N 0) (<= K (- 1)) (>= L 0) (>= (- E A) 0) (>= (- F L) 1) (= (select C L) K))
      (new1 A B C D E F G H I J K L)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M Int) (N Int) )
    (=>
      (and (= M 0) (= N 0) (>= L 0) (>= J 0) (>= (- E A) 0) (>= (- G L) 1) (= (select D L) J))
      (new1 A B C D E F G H I J K L)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) (E Int) (F (Array Int Int)) (G (Array Int Int)) (H (Array Int Int)) (I Int) (J Int) (K Int) (L Int) (M Int) )
    (=>
      (and (= A 0) (= B 0) (= C 0) (= D 1) (>= E 1) (new1 E F G H A B C I J K L M))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
