; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int Int Int (Array Int Int) Int Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) (K (Array Int Int)) )
    (=>
      (and (= I (+ 1 A)) (= J 1) (>= (- C A) 1) (= (store D A B ) K) (new1 I B C K E F G H))
      (new1 A B C D E F G H)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) )
    (=>
      (and (= I 0) (>= H 0) (>= (- A C) 0) (>= (- C H) 1) (>= (- B G) 1) (= (select D H) G))
      (new1 A B C D E F G H)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E Int) (F Int) (G Int) (H Int) (I Int) )
    (=>
      (and (= I 0) (<= (- B G) (- 1)) (>= H 0) (>= (- A C) 0) (>= (- C H) 1) (= (select D H) G))
      (new1 A B C D E F G H)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) )
    (=>
      (and (= A 1) (= B 0) (>= C 1) (new1 B D C E F G H I))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
