; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int Int (Array Int Int) Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B Int) (C (Array Int Int)) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= G (+ 1 A)) (= H 1) (<= (- D I) (- 1)) (>= (- B A) 1) (= (select C A) I) (= (select C A) J) (new1 G B C J E F))
      (new1 A B C D E F)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C (Array Int Int)) (D Int) (E Int) (F Int) (G Int) (H Int) (I Int) )
    (=>
      (and (= G (+ 1 A)) (= H 1) (>= (- B A) 1) (>= (- D I) 0) (= (select C A) I) (new1 G B C D E F))
      (new1 A B C D E F)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C (Array Int Int)) (D Int) (E Int) (F Int) (G Int) (H Int) )
    (=>
      (and (= G 0) (= H 1) (<= (- D E) (- 1)) (>= F 0) (>= (- A B) 0) (>= (- B F) 1) (= (select C F) E))
      (new1 A B C D E F)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) (E (Array Int Int)) (F Int) (G Int) (H Int) )
    (=>
      (and (= A 1) (= B 0) (= C 1) (>= D 1) (= (select E B) F) (new1 C D E F G H))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
