% Automatically generated by smt2map




:- pred new5(int,int,int,int).
:- mode new5(in,in,in,in).
:- pred new4(int,int,int).
:- mode new4(in,in,in).
:- pred new3(int,int,int).
:- mode new3(in,in,in).
:- pred new2(int,int,int).
:- mode new2(in,in,in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new5(A,B,C,D) :- constr((and(E=0,and(F=0,A=0)))).
new4(A,B,C) :- new5(D,A,B,C), constr((and(A+B=<50,and(E=50,and(F=A+B,D=1))))).
new4(A,B,C) :- new5(D,A,B,C), constr((and(A+B>=51,and(E=50,and(F=A+B,D=0))))).
new3(A,B,C) :- new4(D,B,C), constr((and(C>=1,and(E=1,and(D=1+A,F=0))))).
new3(A,B,C) :- new4(D,B,C), constr((and(C=<0,and(E=4,and(D=4+A,F=0))))).
new2(A,B,C) :- new3(A,D,C), constr((and(B>=1,and(D=2,E=0)))).
new2(A,B,C) :- new3(A,D,C), constr((and(B=<0,and(D=5,E=0)))).
new1 :- new2(A,B,C), constr((A=0)).
incorrect :- new1, constr((true)).

