% Automatically generated by smt2map




:- pred inv_main_1(int,int,int,array(int),int,int,int,int,array(int)).
:- mode inv_main_1(in,in,in,in,in,in,in,in,in).
:- pred chc_comp_false.
:- pred inv_main_0(int,int,array(int),int,int,array(int)).
:- mode inv_main_0(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_0(A,B,C,D,E,F) :- constr((C=F&(B=D&A=E))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_0(A,C,D,J,G,I), 
          constr((H=G&(B=A&(~ (select(I,J)=0)&(F=1+J&(E=select(I,J)& ~ (select(D,C)=0))))))).
inv_main_0(A,B,C,D,E,F) :- inv_main_1(G,A,H,C,I,D,E,J,F), 
          constr((select(C,G)=0&(B=1+H&select(F,J)=0))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_1(J,B,C,D,E,F,G,K,I), 
          constr((~ (select(D,J)=0)&(A=1+J&(H=1+K&(~ (select(I,K)=E)&(~ (select(I,K)=0)& ~ (select(D,J)=select(D,C)))))))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_1(J,B,C,D,E,F,G,H,I), 
          constr((~ (select(D,J)=0)&(select(I,H)=0&(select(I,H)=E&(A=1+J& ~ (select(D,J)=select(D,C))))))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_1(A,B,C,D,E,F,G,J,I), 
          constr((~ (select(I,J)=0)&(select(D,A)=0&(select(D,A)=select(D,C)&(H=1+J& ~ (select(I,J)=E)))))).
chc_comp_false :- inv_main_0(A,B,C,D,E,F), 
          constr((~ (select(F,D)=0)&select(C,B)=0)).
chc_comp_false :- inv_main_0(A,B,C,D,E,F), 
          constr((select(F,D)=0& ~ (select(C,B)=0))).
chc_comp_false :- inv_main_0(A,B,C,D,E,F), 
          constr((~ (C=F)&(select(C,B)=0&select(F,D)=0))).
chc_comp_false :- inv_main_1(A,B,C,D,E,F,G,H,I), 
          constr((~ (select(D,A)=0)&(select(I,H)=0&select(D,A)=select(D,C)))).
chc_comp_false :- inv_main_1(A,B,C,D,E,F,G,H,I), 
          constr((select(D,A)=0&(select(I,H)=E& ~ (select(I,H)=0)))).
chc_comp_false :- inv_main_1(A,B,C,D,E,F,G,H,I), 
          constr((J=or(not(C= - 1+F),not(D=I))&(not(select(D,A)=0)&(J&(select(I,H)=E&(not(select(I,H)=0)&select(D,A)=select(D,C))))))).
ff :- chc_comp_false, constr((true)).

