% Automatically generated by smt2map




:- pred end_query.
:- pred inv_main_1(int,int,int,array(int),int,int,int,array(int)).
:- mode inv_main_1(in,in,in,in,in,in,in,in).
:- pred inv_main_2(int,int,int,int,array(int),int,int,int,int,array(int)).
:- mode inv_main_2(in,in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_1(A,B,C,D,E,F,G,H) :- constr((0=F&(0=B&(D=H&(A=E&C=G))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), constr((~ (G=<F)&C=<B)).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), constr((G=<F& ~ (C=<B))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), constr((~ (D=H)&(C=<B&G=<F))).
inv_main_2(A,B,C,D,E,F,G,H,I,J) :- inv_main_1(A,B,D,E,F,G,I,J), 
          constr((H=G&(C=B&(~ (I=<G)& ~ (D=<B))))).
end_query :- inv_main_2(A,B,C,D,E,F,G,H,I,J), 
          constr((K=(select(J,F+4*G)=<select(J,F+4*H))&(not(K)&(D=<C&not(I=<H))))).
end_query :- inv_main_2(A,B,C,D,E,F,G,H,I,J), 
          constr((K=(select(J,F+4*G)=<select(J,F+4*H))&(K&(D=<C&not(I=<H))))).
end_query :- inv_main_2(A,B,C,D,E,F,G,H,I,J), 
          constr((K=(select(E,A+4*C)=<select(E,A+4*B))&(K&(I=<H&not(D=<C))))).
end_query :- inv_main_2(A,B,C,D,E,F,G,H,I,J), 
          constr((K=(select(E,A+4*C)=<select(E,A+4*B))&(not(K)&(I=<H&not(D=<C))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_2(A,I,J,C,D,E,K,L,G,H), 
          constr((B=1+I&(C=<J&(G=<L&F=1+K)))).
inv_main_2(A,B,C,D,E,F,G,H,I,J) :- inv_main_2(A,B,K,D,L,F,G,M,I,N), 
          constr((O=store(L,A+4*B,select(L,A+4*K))&(P=(select(N,F+4*G)=<select(N,F+4*M))&(Q=(select(L,A+4*K)=<select(L,A+4*B))&(R=store(N,F+4*G,select(N,F+4*M))&(S=store(O,A+4*K,select(L,A+4*B))&(T=store(R,F+4*M,select(N,F+4*G))&and(J=T,C=1+K,H=1+M,Q,not(P),not(D=<K),not(I=<M),E=S)))))))).
inv_main_2(A,B,C,D,E,F,G,H,I,J) :- inv_main_2(A,B,K,D,L,F,G,M,I,J), 
          constr((N=store(L,A+4*B,select(L,A+4*K))&(O=(select(J,F+4*G)=<select(J,F+4*M))&(P=(select(L,A+4*K)=<select(L,A+4*B))&(Q=store(N,A+4*K,select(L,A+4*B))&and(C=1+K,H=1+M,P,O,not(D=<K),not(I=<M),E=Q)))))).
inv_main_2(A,B,C,D,E,F,G,H,I,J) :- inv_main_2(A,B,K,D,E,F,G,L,I,M), 
          constr((N=store(M,F+4*G,select(M,F+4*L))&(O=(select(M,F+4*G)=<select(M,F+4*L))&(P=(select(E,A+4*K)=<select(E,A+4*B))&(Q=store(N,F+4*L,select(M,F+4*G))&and(C=1+K,H=1+L,not(P),not(O),not(D=<K),not(I=<L),J=Q)))))).
inv_main_2(A,B,C,D,E,F,G,H,I,J) :- inv_main_2(A,B,K,D,E,F,G,L,I,J), 
          constr((M=(select(J,F+4*G)=<select(J,F+4*L))&(N=(select(E,A+4*K)=<select(E,A+4*B))&(C=1+K&(not(I=<L)&(not(D=<K)&(M&(not(N)&H=1+L)))))))).
ff :- end_query, constr((true)).

