% Automatically generated by smt2map




:- pred inv_main_3(int,int,int,array(int),int,int,int,array(int)).
:- mode inv_main_3(in,in,in,in,in,in,in,in).
:- pred end_query.
:- pred inv_main_1(int,int,int,array(int),int,int,int,array(int)).
:- mode inv_main_1(in,in,in,in,in,in,in,in).
:- pred inv_main_2(int,int,int,array(int),int,int,int,array(int)).
:- mode inv_main_2(in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

end_query :- 
          constr((A=B&(C>=0&(D>=0&(E>=0&(F>=0&(G>=0&(H>=0&(C=E&(D=F&(I=J&(~ (I=0)&(J=0&H=G))))))))))))).
inv_main_1(A,B,C,D,E,F,G,H) :- 
          constr((I=J&(A>=0&(K>=0&(E>=0&(L>=0&(G>=0&(C>=0&(F= - 1+M&(A=E&(N=M&(~ (N=0)&(K=L&(~ (M=0)&(C=G&(B= - 1+N&(D=store(I,K,C)&H=store(J,L,G)))))))))))))))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((I=not(select(D,C+B)=41)&(select(H,G+F)=41&(B=0&(not(F=0)&I))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((I=not(select(D,C+B)=41)&(select(H,G+F)=41&(B=0&(F=0&I))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((I=not(select(H,G+F)=41)&(I&(not(B=0)&(F=0&select(D,C+B)=41))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((I=not(select(H,G+F)=41)&(I&(B=0&(F=0&select(D,C+B)=41))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((I=not(select(H,G+F)=41)&(J=not(select(D,C+B)=41)&(not(D=H)&(B=0&(F=0&(I&J))))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_1(A,I,C,D,E,J,G,H), 
          constr((K=not(select(D,C+I)=41)&(L=not(select(H,G+J)=41)&(K&(F= - 1+J&(B= - 1+I&(not(I=0)&(not(J=0)&L)))))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_1(A,I,C,D,E,F,G,H), 
          constr((J=not(select(D,C+I)=41)&(K=or(F=0,select(H,G+F)=41)&(J&(K&(B= - 1+I&not(I=0))))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_1(A,B,C,D,E,I,G,H), 
          constr((J=not(select(H,G+I)=41)&(K=or(B=0,select(D,C+B)=41)&(J&(K&(F= - 1+I&not(I=0))))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_1(A,I,C,J,E,K,G,L), 
          constr((H=store(L,G+K,0)&(B=1+I&(~ (I=0)&(~ (K=0)&(F=1+K&(select(L,G+K)=41&(select(J,C+I)=41&D=store(J,C+I,0))))))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_1(A,I,C,J,E,K,G,L), 
          constr((H=store(L,G+K,0)&(B=1+I&(~ (I=0)&(K=0&(F=1+K&(select(L,G+K)=41&(select(J,C+I)=41&D=store(J,C+I,0))))))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_1(A,I,C,J,E,K,G,L), 
          constr((H=store(L,G+K,0)&(B=1+I&(I=0&(~ (K=0)&(F=1+K&(select(L,G+K)=41&(select(J,C+I)=41&D=store(J,C+I,0))))))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_1(A,I,C,J,E,K,G,L), 
          constr((H=store(L,G+K,0)&(B=1+I&(I=0&(K=0&(F=1+K&(select(L,G+K)=41&(select(J,C+I)=41&D=store(J,C+I,0))))))))).
end_query :- inv_main_2(A,B,C,D,E,F,G,H), 
          constr((I=not(select(H,G+F)=9)&(J=not(select(D,C+B)=32)&(K=not(select(D,C+B)=61)&(L=not(select(D,C+B)=9)&(M=not(select(H,G+F)=32)&(I&(J&(K&(L&(M&select(H,G+F)=61))))))))))).
end_query :- inv_main_2(A,B,C,D,E,F,G,H), 
          constr((I=not(select(H,G+F)=9)&(J=not(select(D,C+B)=32)&(K=not(select(D,C+B)=9)&(L=not(select(H,G+F)=32)&(M=not(select(H,G+F)=61)&(I&(J&(select(D,C+B)=61&(K&(L&M))))))))))).
end_query :- inv_main_2(A,B,C,D,E,F,G,H), 
          constr((I=not(select(H,G+F)=32)&(J=not(select(H,G+F)=61)&(K=not(select(H,G+F)=9)&(L=not(select(D,C+B)=32)&(M=not(select(D,C+B)=61)&(N=not(select(D,C+B)=9)&(not(D=H)&(I&(J&(K&(L&(M&N))))))))))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,I,C,D,E,J,G,H), 
          constr((select(D,C+I)=32&(F=1+J&(B=1+I&select(H,G+J)=32)))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,I,C,D,E,J,G,H), 
          constr((K=not(select(H,G+J)=32)&(select(D,C+I)=32&(F=1+J&(B=1+I&(K&select(H,G+J)=9)))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,I,C,D,E,J,G,H), 
          constr((K=not(select(D,C+I)=32)&(select(D,C+I)=9&(F=1+J&(B=1+I&(select(H,G+J)=32&K)))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,I,C,D,E,J,G,H), 
          constr((K=not(select(H,G+J)=32)&(L=not(select(D,C+I)=32)&(select(D,C+I)=9&(F=1+J&(B=1+I&(K&(select(H,G+J)=9&L)))))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,I,C,D,E,F,G,H), 
          constr((J=not(select(H,G+F)=9)&(K=not(select(H,G+F)=32)&(L=or(select(H,G+F)=32,J)&and(K,B=1+I,L,select(D,C+I)=32))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,I,C,D,E,F,G,H), 
          constr((J=not(select(H,G+F)=9)&(K=not(select(H,G+F)=32)&(L=not(select(D,C+I)=32)&(M=or(select(H,G+F)=32,J)&and(L,K,B=1+I,M,select(D,C+I)=9)))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,B,C,D,E,I,G,H), 
          constr((J=not(select(D,C+B)=32)&(K=not(select(D,C+B)=9)&(L=or(select(D,C+B)=32,K)&and(select(H,G+I)=32,F=1+I,L,J))))).
inv_main_2(A,B,C,D,E,F,G,H) :- inv_main_2(A,B,C,D,E,I,G,H), 
          constr((J=not(select(D,C+B)=32)&(K=not(select(D,C+B)=9)&(L=not(select(H,G+I)=32)&(M=or(select(D,C+B)=32,K)&and(select(H,G+I)=9,L,F=1+I,M,J)))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_2(A,B,C,D,E,F,G,H), 
          constr((I=not(select(D,C+B)=9)&(J=not(select(H,G+F)=32)&(K=not(select(H,G+F)=9)&(L=not(select(D,C+B)=32)&(I&(J&(select(H,G+F)=61&(K&(L&select(D,C+B)=61)))))))))).
end_query :- inv_main_3(A,B,C,D,E,F,G,H), 
          constr((I=not(store(D,A,smt_plus(1,C,B))=store(H,E,smt_plus(1,G,F)))&(J=not(select(H,smt_plus(1,G,F))=32)&(K=not(select(H,smt_plus(1,G,F))=9)&(L=not(select(D,smt_plus(1,C,B))=32)&(M=not(select(D,smt_plus(1,C,B))=9)&(I&(J&(K&(L&M)))))))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,I,C,D,E,J,G,H), 
          constr((select(D,smt_plus(1,C,I))=32&(F=1+J&(B=1+I&select(H,smt_plus(1,G,J))=32)))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,I,C,D,E,J,G,H), 
          constr((K=not(select(H,smt_plus(1,G,J))=32)&(select(D,smt_plus(1,C,I))=32&(F=1+J&(B=1+I&(K&select(H,smt_plus(1,G,J))=9)))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,I,C,D,E,J,G,H), 
          constr((K=not(select(D,smt_plus(1,C,I))=32)&(select(D,smt_plus(1,C,I))=9&(F=1+J&(B=1+I&(select(H,smt_plus(1,G,J))=32&K)))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,I,C,D,E,J,G,H), 
          constr((K=not(select(H,smt_plus(1,G,J))=32)&(L=not(select(D,smt_plus(1,C,I))=32)&(select(D,smt_plus(1,C,I))=9&(F=1+J&(B=1+I&(K&(select(H,smt_plus(1,G,J))=9&L)))))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,I,C,D,E,F,G,H), 
          constr((J=not(select(H,smt_plus(1,G,F))=9)&(K=not(select(H,smt_plus(1,G,F))=32)&(L=or(select(H,smt_plus(1,G,F))=32,J)&and(K,B=1+I,L,select(D,smt_plus(1,C,I))=32))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,I,C,D,E,F,G,H), 
          constr((J=not(select(H,smt_plus(1,G,F))=9)&(K=not(select(H,smt_plus(1,G,F))=32)&(L=not(select(D,smt_plus(1,C,I))=32)&(M=or(select(H,smt_plus(1,G,F))=32,J)&and(L,K,B=1+I,M,select(D,smt_plus(1,C,I))=9)))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,B,C,D,E,I,G,H), 
          constr((J=not(select(D,smt_plus(1,C,B))=32)&(K=not(select(D,smt_plus(1,C,B))=9)&(L=or(select(D,smt_plus(1,C,B))=32,K)&and(select(H,smt_plus(1,G,I))=32,F=1+I,L,J))))).
inv_main_3(A,B,C,D,E,F,G,H) :- inv_main_3(A,B,C,D,E,I,G,H), 
          constr((J=not(select(D,smt_plus(1,C,B))=32)&(K=not(select(D,smt_plus(1,C,B))=9)&(L=not(select(H,smt_plus(1,G,I))=32)&(M=or(select(D,smt_plus(1,C,B))=32,K)&and(select(H,smt_plus(1,G,I))=9,L,F=1+I,M,J)))))).
ff :- end_query, constr((true)).

