% Automatically generated by smt2map




:- pred fail.
:- pred inv(int,int).
:- mode inv(in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv(A,B) :- constr((and(B=1,A=1))).
inv(A,B) :- inv(C,D), constr((and(A=2*C,B=ite(16=<D,C mod 16,2*D)))).
fail :- inv(A,B), constr((and(~ (0=B),~ (A=<16)))).
ff :- fail, constr((true)).

