% Automatically generated by smt2map




:- pred 'main@verifier.error.split'.
:- pred 'main@bb28.i'(int,array(int),int,array(int),int,int,int,array(int),int).
:- mode 'main@bb28.i'(in,in,in,in,in,in,in,in,in).
:- pred 'main@entry'(int,int).
:- mode 'main@entry'(in,in).
:- pred 'main@bb13.i'(int,int,int,array(int),int,array(int),int,int,array(int)).
:- mode 'main@bb13.i'(in,in,in,in,in,in,in,in,in).
:- pred 'main@bb55.i'(int,array(int),int,array(int),int,array(int),int,int).
:- mode 'main@bb55.i'(in,in,in,in,in,in,in,in).
:- pred 'main@bb78.i'(int,array(int),int,array(int),int,int).
:- mode 'main@bb78.i'(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A,B) :- constr((true)).
'main@bb13.i'(A,B,C,D,E,F,G,H,I) :- 'main@entry'(A,J), 
          constr((~ ((H=<0)=K)&(L=true&(K=true&(and(M,L)&(not(L)&(C=N&(not(L)&(not(M)&(N=0&(not(L)&(not(M)&(F=O&(not(L)&(not(M)&(D=P&(not(L)&(not(M)&(O=Q&(not(L)&(not(M)&(P=R&(not(L)&(not(M)&(~ (G=<0)&(~ (E=<0)&(~ (B=<0)&S=J))))))))))))))))))))))))))).
'main@bb13.i'(A,B,C,D,E,F,G,H,I) :- 'main@bb13.i'(A,B,J,K,E,L,G,H,I), 
          constr((~ ((H=<J)=M)&(N=true&(and(O,P)&(not(O)&(not(E=<0)&(not(O)&(not(B=<0)&(not(O)&(Q=1+J&(not(O)&(R=E+J&(not(O)&(S=A&(not(O)&(T=B+J&(not(O)&(U=A&(not(O)&(V=store(L,R,W)&(not(O)&(X=store(K,T,Y)&(not(O)&(and(O,N)&(not(N)&(C=Z&(not(N)&(not(O)&(Z=Q&(not(N)&(not(O)&(F=A1&(not(N)&(not(O)&(D=B1&(not(N)&(not(O)&(A1=V&(not(N)&(not(O)&(B1=X&(not(N)&(not(O)&(M&(not(O)&(not(P)&(E=<0&(not(O)&(not(R=<0)&(B=<0&(not(O)&not(T=<0)))))))))))))))))))))))))))))))))))))))))))))))))))).
'main@bb28.i'(A,B,C,D,E,F,G,H,I) :- 'main@bb13.i'(J,A,K,B,C,D,G,I,L), 
          constr((~ ((I=<K)=M)&(N=true&(and(O,N)&(not(N)&(not(M)&(not(N)&(not(O)&(F=P&(not(N)&(not(O)&(E=Q&(not(N)&(not(O)&(P=1&(not(N)&(not(O)&(Q=0&(not(N)&(not(O)&(R=L&(not(N)&(not(O)&(H=R&(not(N)&not(O)))))))))))))))))))))))))).
'main@bb28.i'(A,B,C,D,E,F,G,H,I) :- 'main@bb28.i'(A,B,C,D,J,K,G,L,I), 
          constr((~ ((I=<J)=M)&(N=true&(and(O,P)&(not(O)&(not(G=<0)&(not(O)&(not(C=<0)&(not(O)&(not(A=<0)&(not(O)&(Q=select(B,R)&(not(O)&(S=ite(T,K,0)&(not(O)&(U=G+J&(not(O)&(V=select(D,W)&(not(O)&(R=A+J&(not(O)&(X=1+J&(not(O)&(W=C+J&(not(O)&(T=(Q=V)&(not(O)&(Y=store(L,U,Q)&(not(O)&(and(O,N)&(not(N)&(F=Z&(not(N)&(not(O)&(E=A1&(not(N)&(not(O)&(Z=S&(not(N)&(not(O)&(A1=X&(not(N)&(not(O)&(B1=Y&(not(N)&(not(O)&(H=B1&(not(N)&(not(O)&(M&(not(O)&(not(P)&(G=<0&(not(O)&(not(U=<0)&(not(W=<0)&(C=<0&(not(O)&(not(R=<0)&(A=<0&not(O))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))).
'main@bb55.i'(A,B,C,D,E,F,G,H) :- 'main@bb28.i'(A,B,C,D,I,J,E,F,G), 
          constr((~ ((G=<I)=K)&(L=true&(and(L,M)&(not(L)&(and(N,M)&(not(M)&(O=(J=0)&(not(M)&(not(N)&(not(M)&(not(K)&(not(O)&(not(M)&(not(L)&(H=P&(not(M)&(not(L)&(P=0&(not(M)&not(L))))))))))))))))))))).
'main@bb55.i'(A,B,C,D,E,F,G,H) :- 'main@bb55.i'(A,B,C,D,E,F,G,I), 
          constr((~ ((G=<I)=J)&(K=true&(and(L,M)&(not(L)&(not(A=<0)&(not(L)&(not(C=<0)&(not(L)&(N=C+I&(not(L)&(O=A+I&(not(L)&(P=select(B,O)&(not(L)&(Q=select(D,N)&(not(L)&(R=(P=Q)&(not(L)&(and(K,S)&(not(K)&(and(L,S)&(not(S)&(T=1+I&(not(S)&(not(L)&(not(S)&(R&(not(M)&(not(L)&(J&(not(O=<0)&(not(L)&(A=<0&(C=<0&(not(N=<0)&(not(L)&(H=U&(not(S)&(not(K)&(U=T&(not(S)&not(K))))))))))))))))))))))))))))))))))))))))))).
'main@bb78.i'(A,B,C,D,E,F) :- 'main@bb28.i'(A,B,G,H,I,J,C,D,F), 
          constr((~ ((F=<I)=K)&(L=true&(and(M,N)&(not(M)&(O=(J=0)&(not(M)&(and(M,L)&(not(L)&(not(N)&(not(M)&(not(K)&(not(M)&(not(L)&(O&(E=P&(not(L)&(not(M)&(P=0&(not(L)&not(M))))))))))))))))))))).
'main@bb78.i'(A,B,C,D,E,F) :- 'main@bb55.i'(A,B,G,H,C,D,F,I), 
          constr((~ ((F=<I)=J)&(K=true&(and(L,K)&(not(K)&(not(L)&(not(K)&(not(J)&(E=M&(not(K)&(not(L)&(M=0&(not(K)&not(L)))))))))))))).
'main@bb78.i'(A,B,C,D,E,F) :- 'main@bb78.i'(A,B,C,D,G,F), 
          constr((~ ((F=<G)=H)&(I=true&(H=true&(and(J,K)&(not(J)&(L=1+G&(not(J)&(and(J,I)&(not(I)&(and(K,M)&(not(K)&(not(C=<0)&(not(K)&(not(A=<0)&(not(K)&(N=A+G&(not(K)&(O=select(B,N)&(not(K)&(P=select(D,Q)&(not(K)&(Q=C+G&(not(K)&(R=(O=P)&(not(K)&(not(K)&(not(J)&(R&(E=S&(not(I)&(not(J)&(S=L&(not(I)&(not(J)&(not(Q=<0)&(not(K)&(C=<0&(A=<0&(not(N=<0)&not(K))))))))))))))))))))))))))))))))))))))))).
'main@verifier.error.split' :- 'main@bb55.i'(A,B,C,D,E,F,G,H), 
          constr((~ ((G=<H)=I)&(J=true&(and(J,K)&(not(J)&(and(K,L)&(not(K)&(and(L,M)&(not(L)&(and(N,M)&(not(M)&(not(C=<0)&(not(M)&(not(A=<0)&(not(M)&(O=select(B,P)&(not(M)&(Q=C+H&(not(M)&(R=select(D,Q)&(not(M)&(P=A+H&(not(M)&(S=(O=R)&(not(M)&(not(M)&(not(N)&(I&(not(M)&(not(S)&(not(L)&(C=<0&(not(Q=<0)&(not(M)&(not(P=<0)&(not(M)&A=<0)))))))))))))))))))))))))))))))))))).
'main@verifier.error.split' :- 'main@bb78.i'(A,B,C,D,E,F), 
          constr((~ ((F=<E)=G)&(G=true&(H=true&(and(H,I)&(not(H)&(and(I,J)&(not(I)&(and(J,K)&(not(J)&(and(L,K)&(not(K)&(not(C=<0)&(not(K)&(not(A=<0)&(not(K)&(M=select(B,N)&(not(K)&(O=C+E&(not(K)&(P=select(D,O)&(not(K)&(N=A+E&(not(K)&(Q=(M=P)&(not(K)&(not(K)&(not(Q)&(not(J)&(C=<0&(not(O=<0)&(not(K)&(not(N=<0)&(not(K)&A=<0)))))))))))))))))))))))))))))))))).
ff :- 'main@verifier.error.split', constr((true)).

