% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,array(int),int,int,int,int).
:- mode new1(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new1(A,B,C,D,E,F) :- new1(A,B,G,D,E,H), 
          constr((select(B,F)=G&(select(B,F)=I&(A-F>=1&(C-I=< - 1&(J=1&H=1+F)))))).
new1(A,B,C,D,E,F) :- new1(A,B,C,D,E,G), 
          constr((select(B,F)=H&(C-H>=0&(A-F>=1&(I=1&G=1+F))))).
new1(A,B,C,D,E,F) :- 
          constr((select(B,E)=D&(A-E>=1&(F-A>=0&(E>=0&(C-D=< - 1&G=0)))))).
incorrect :- new1(A,B,C,D,E,F), constr((select(B,G)=C&(A>=1&(F=1&(G=0&H=1))))).

