% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new1(in,in,in,in,in,in,in,in,in).
:- pred new2(int,array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new2(in,in,in,in,in,in,in,in,in).
:- pred new3(int,array(int),array(int),array(int),array(int),int,int,int,int).
:- mode new3(in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new3(A,B,C,D,E,F,G,H,I) :- new3(A,B,C,D,J,F,G,H,K), 
          constr((store(E,I,L)=J&(select(D,I)=L&(A-I>=1&(M=1&K=1+I))))).
new3(A,B,C,D,E,F,G,H,I) :- 
          constr((select(E,H)=F&(select(B,H)=G&(A-H>=1&(I-A>=0&(H>=0&(G-F=< - 1&J=0))))))).
new3(A,B,C,D,E,F,G,H,I) :- 
          constr((select(E,H)=F&(select(B,H)=G&(G-F>=1&(A-H>=1&(I-A>=0&(H>=0&J=0))))))).
new2(A,B,C,D,E,F,G,H,I) :- new2(A,B,C,J,E,F,G,H,K), 
          constr((store(D,I,L)=J&(select(C,I)=L&(A-I>=1&(M=1&K=1+I))))).
new2(A,B,C,D,E,F,G,H,I) :- new3(A,B,C,D,E,F,G,H,J), constr((I-A>=0&J=0)).
new1(A,B,C,D,E,F,G,H,I) :- new1(A,B,J,D,E,F,G,H,K), 
          constr((store(C,I,L)=J&(select(B,I)=L&(A-I>=1&(M=1&K=1+I))))).
new1(A,B,C,D,E,F,G,H,I) :- new2(A,B,C,D,E,F,G,H,J), constr((I-A>=0&J=0)).
incorrect :- new1(A,B,C,D,E,F,G,H,I), constr((A>=1&(I=0&J=1))).

