% Automatically generated by smt2map




:- pred inv_main_42(int,int,int,int,array(int),int,int,int,array(int)).
:- mode inv_main_42(in,in,in,in,in,in,in,in,in).
:- pred end_query.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_42(A,B,C,D,E,F,G,H,I) :- 
          constr((and(E=J,and(D=H,and(K=F,and(D>=0,and(I=store(store(J,F,1),4+F,1),and(1=A,and(1=B,and(2=C,2=G)))))))))).
end_query :- inv_main_42(A,B,C,D,E,F,G,H,I), 
          constr((and(J=(B=select(I,smt_plus(- 4,F,4*G))),and(H=<G,and(D=<C,not(J)))))).
inv_main_42(A,B,C,D,E,F,G,H,I) :- inv_main_42(J,A,K,D,E,F,L,H,M), 
          constr((and(N=select(M,smt_plus(- 4,F,4*L))+select(M,smt_plus(- 8,F,4*L)),and(O=(I=store(M,F+4*L,N)),and(B=A+J,and(C=1+K,and(G=1+L,and(not(H=<L),and(not(D=<K),O))))))))).
inv_main_42(A,B,C,D,E,F,G,H,I) :- inv_main_42(J,A,K,D,E,F,G,H,I), 
          constr((and(C=1+K,and(H=<G,and(not(D=<K),B=A+J))))).
inv_main_42(A,B,C,D,E,F,G,H,I) :- inv_main_42(A,B,C,D,E,F,J,H,K), 
          constr((and(L=select(K,smt_plus(- 4,F,4*J))+select(K,smt_plus(- 8,F,4*J)),and(M=(I=store(K,F+4*J,L)),and(G=1+J,and(not(H=<J),and(D=<C,M))))))).
ff :- end_query, constr((true)).

