% Automatically generated by smt2map




:- pred end_query.
:- pred inv_main_1(int,int,int,array(int),int,int,int,array(int)).
:- mode inv_main_1(in,in,in,in,in,in,in,in).
:- pred inv_main_0(int,int,array(int),int,int,array(int)).
:- mode inv_main_0(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_0(A,B,C,D,E,F) :- constr((and(B=E,and(A=D,C=F)))).
end_query :- inv_main_0(A,B,C,D,E,F), 
          constr((and(~ (select(F,E)=0),select(C,B)=0))).
end_query :- inv_main_0(A,B,C,D,E,F), 
          constr((and(select(F,E)=0,~ (select(C,B)=0)))).
end_query :- inv_main_0(A,B,C,D,E,F), 
          constr((and(select(C,B)=0,and(select(F,E)=0,not(C=F))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_0(A,C,D,E,G,H), 
          constr((and(not(select(D,C)=0),and(not(select(H,G)=0),and(B=A,0=F))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((and(select(D,A)=select(D,C),and(select(H,E+F)=0,not(select(D,A)=0))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((and(I=not(select(H,E+F)=0),and(I,and(select(H,G)=select(H,E+F),select(D,A)=0))))).
end_query :- inv_main_1(A,B,C,D,E,F,G,H), 
          constr((and(I=not(select(H,E+F)=0),and(select(D,A)=select(D,C),and(I,and(select(H,G)=select(H,E+F),and(or(not(D=H),not(C=G)),not(select(D,A)=0)))))))).
inv_main_0(A,B,C,D,E,F) :- inv_main_1(G,A,H,C,D,I,J,F), 
          constr((and(select(C,G)=0,and(E=1+J,and(B=1+H,select(F,D+I)=0))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_1(I,B,C,D,E,J,G,H), 
          constr((and(and(not(select(D,I)=select(D,C)),K,L,F=1+J,A=1+I,not(select(D,I)=0)),and(K=not(select(H,E+J)=0),L=not(select(H,G)=select(H,E+J)))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_1(I,B,C,D,E,F,G,H), 
          constr((and(J=or(select(H,G)=select(H,E+F),select(H,E+F)=0),and(not(select(D,I)=select(D,C)),and(A=1+I,and(J,not(select(D,I)=0))))))).
inv_main_1(A,B,C,D,E,F,G,H) :- inv_main_1(A,B,C,D,E,I,G,H), 
          constr((and(and(J,F=1+I,or(select(D,A)=select(D,C),select(D,A)=0),K),and(J=not(select(H,G)=select(H,E+I)),K=not(select(H,E+I)=0))))).
ff :- end_query, constr((true)).

