% Automatically generated by smt2map




:- pred inv_main_42(int,int,int,array(int),int,int,int,int,int,array(int)).
:- mode inv_main_42(in,in,in,in,in,in,in,in,in,in).
:- pred chc_comp_false.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_42(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(and(select(J,K)=select(J,L),not(select(J,K)=0),select(D,M)=select(D,N),not(select(D,M)=0),H=1+L,G=1+K,F=select(J,L),E=select(J,K),A=1+N,B=1+M,not(C=0),C=I,N=L,M=K,O,D=J),O=not(ite(I>=0,I,- 1*I)=<0)))).
inv_main_42(A,B,C,D,E,F,G,H,I,J) :- inv_main_42(K,L,M,D,N,O,P,Q,R,J), 
          constr((and(S=(ite(R>=1,- 1+R,1+ - 1*R)=<0),and(not(select(D,L)=0),and(select(J,P)=select(J,Q),and(not(select(J,P)=0),and(I= - 1+R,and(H=1+Q,and(G=1+P,and(F=select(J,Q),and(E=select(J,P),and(C= - 1+M,and(B=1+L,and(A=1+K,and(not(M=1),and(not(S),select(D,L)=select(D,K))))))))))))))))).
inv_main_42(A,B,C,D,E,F,G,H,I,J) :- inv_main_42(K,L,M,D,E,F,G,H,I,J), 
          constr((and(N=(ite(I>=1,- 1+I,1+ - 1*I)=<0),and(O=or(select(J,G)=0,not(select(J,G)=select(J,H)),N),and(not(select(D,L)=0),and(C= - 1+M,and(B=1+L,and(A=1+K,and(not(M=1),and(O,select(D,L)=select(D,K))))))))))).
inv_main_42(A,B,C,D,E,F,G,H,I,J) :- inv_main_42(A,B,C,D,K,L,M,N,O,J), 
          constr((and(and(not(select(J,M)=0),I= - 1+O,H=1+N,G=1+M,F=select(J,N),E=select(J,M),not(P),Q,select(J,M)=select(J,N)),and(P=(ite(O>=1,- 1+O,1+ - 1*O)=<0),Q=or(select(D,B)=0,not(select(D,B)=select(D,A)),C=1))))).
chc_comp_false :- 
          constr((and(and(select(A,B)=select(A,C),not(select(A,B)=0),D=0,D=E,F=C,G=B,H,I=A),H=not(ite(E>=0,E,- 1*E)=<0)))).
chc_comp_false :- 
          constr((and(and(select(A,B)=select(A,C),not(select(A,B)=0),not(select(D,E)=select(D,F)),not(G=0),G=H,F=C,E=B,I,D=A),I=not(ite(H>=0,H,- 1*H)=<0)))).
chc_comp_false :- 
          constr((and(and(select(A,B)=select(A,C),not(select(A,B)=0),select(D,E)=select(D,F),select(D,E)=0,not(G=0),G=H,F=C,E=B,I,D=A),I=not(ite(H>=0,H,- 1*H)=<0)))).
chc_comp_false :- 
          constr((and(and(select(A,B)=0,select(C,D)=select(C,E),not(select(C,D)=0),not(F=0),F=G,E=H,D=B,I,C=A),I=not(ite(G>=0,G,- 1*G)=<0)))).
chc_comp_false :- 
          constr((and(and(not(select(A,B)=select(A,C)),not(select(A,B)=0),select(D,E)=select(D,F),not(select(D,E)=0),not(G=0),G=H,F=C,E=B,I,D=A),I=not(ite(H>=0,H,- 1*H)=<0)))).
chc_comp_false :- 
          constr((and(select(A,B)=select(A,C),and(not(select(A,B)=0),and(not(D=0),and(D=E,and(C=F,and(B=G,and(ite(E>=0,E,- 1*E)=<0,A=H))))))))).
chc_comp_false :- 
          constr((and(and(select(A,B)=0,C=0,C=D,E=F,G=B,H,or(not(I),not(J=A)),J=A),and(H=not(ite(D>=0,D,- 1*D)=<0),I=(0=select(A,B)+ - 1*select(A,F)))))).
chc_comp_false :- 
          constr((and(and(not(select(A,B)=select(A,C)),not(select(A,B)=0),D=0,D=E,F=C,G=B,H,or(not(I),not(J=A)),J=A),and(H=not(ite(E>=0,E,- 1*E)=<0),I=(0=select(A,B)+ - 1*select(A,C)))))).
chc_comp_false :- 
          constr((and(and(select(A,B)=0,not(select(C,D)=select(C,E)),not(F=0),F=G,E=H,D=B,I,or(not(C=A),not(J)),C=A),and(I=not(ite(G>=0,G,- 1*G)=<0),J=(select(C,D)+ - 1*select(C,E)=select(A,B)+ - 1*select(A,H)))))).
chc_comp_false :- 
          constr((and(and(not(select(A,B)=select(A,C)),not(select(A,B)=0),not(select(D,E)=select(D,F)),not(G=0),G=H,F=C,E=B,I,or(not(D=A),not(J)),D=A),and(I=not(ite(H>=0,H,- 1*H)=<0),J=(select(D,E)+ - 1*select(D,F)=select(A,B)+ - 1*select(A,C)))))).
chc_comp_false :- 
          constr((and(and(not(select(A,B)=select(A,C)),not(D=0),D=E,C=F,B=G,ite(E>=0,E,- 1*E)=<0,or(not(A=H),not(I)),A=H),I=(select(A,B)+ - 1*select(A,C)=0)))).
chc_comp_false :- 
          constr((and(and(select(A,B)=0,select(C,D)=select(C,E),select(C,D)=0,not(F=0),F=G,E=H,D=B,I,or(not(J),not(C=A)),C=A),and(I=not(ite(G>=0,G,- 1*G)=<0),J=(0=select(A,B)+ - 1*select(A,H)))))).
chc_comp_false :- 
          constr((and(and(not(select(A,B)=select(A,C)),not(select(A,B)=0),select(D,E)=select(D,F),select(D,E)=0,not(G=0),G=H,F=C,E=B,I,or(not(J),not(D=A)),D=A),and(I=not(ite(H>=0,H,- 1*H)=<0),J=(0=select(A,B)+ - 1*select(A,C)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(select(J,G)=0,not(C=1),not(K),or(not(L),not(D=J)),not(select(D,B)=select(D,A))),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=(select(D,B)+ - 1*select(D,A)=select(J,G)+ - 1*select(J,H)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(not(select(J,G)=select(J,H)),not(select(J,G)=0),not(C=1),not(K),or(not(L),not(D=J)),not(select(D,B)=select(D,A))),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=(select(D,B)+ - 1*select(D,A)=select(J,G)+ - 1*select(J,H)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(not(C=1),K,or(not(D=J),not(L)),not(select(D,B)=select(D,A))),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=(select(D,B)+ - 1*select(D,A)=E+ - 1*F))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(select(D,B)=0,select(J,G)=0,not(C=1),not(K),or(not(L),not(D=J)),select(D,B)=select(D,A)),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=(0=select(J,G)+ - 1*select(J,H)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(select(D,B)=0,not(select(J,G)=select(J,H)),not(select(J,G)=0),not(C=1),not(K),or(not(L),not(D=J)),select(D,B)=select(D,A)),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=(0=select(J,G)+ - 1*select(J,H)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(select(D,B)=0,not(C=1),K,or(not(D=J),L),select(D,B)=select(D,A)),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=not(0=E+ - 1*F))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(C=1,not(K),or(not(L),not(D=J)),select(J,G)=0),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=(0=select(J,G)+ - 1*select(J,H)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(not(select(J,G)=0),C=1,not(K),or(not(L),not(D=J)),not(select(J,G)=select(J,H))),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=(0=select(J,G)+ - 1*select(J,H)))))).
chc_comp_false :- inv_main_42(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(K,or(not(D=J),L),C=1),and(K=(ite(I>=1,- 1+I,1+ - 1*I)=<0),L=not(0=E+ - 1*F))))).
ff :- chc_comp_false, constr((true)).

