% Automatically generated by smt2map




:- pred inv_main_1(int,int,int,array(int),int,int,int,int,array(int)).
:- mode inv_main_1(in,in,in,in,in,in,in,in,in).
:- pred chc_comp_false.
:- pred inv_main_0(int,int,array(int),int,int,array(int)).
:- mode inv_main_0(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv_main_0(A,B,C,D,E,F) :- constr((and(A=E,and(B=D,C=F)))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_0(A,C,D,J,G,I), 
          constr((and(not(select(D,C)=0),and(E=select(I,J),and(F=1+J,and(not(select(I,J)=0),and(0=B,H=G))))))).
inv_main_0(A,B,C,D,E,F) :- inv_main_1(A,G,H,C,I,D,E,J,F), 
          constr((and(select(F,J)=0,and(B=1+H,select(C,A+G)=0)))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_1(A,J,C,D,E,F,G,K,I), 
          constr((and(and(L,not(select(I,K)=0),not(select(I,K)=E),H=1+K,B=1+J,M),and(L=not(select(D,C)=select(D,A+J)),M=not(select(D,A+J)=0))))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_1(A,J,C,D,E,F,G,H,I), 
          constr((and(and(K,B=1+J,or(select(I,H)=E,select(I,H)=0),L),and(K=not(select(D,C)=select(D,A+J)),L=not(select(D,A+J)=0))))).
inv_main_1(A,B,C,D,E,F,G,H,I) :- inv_main_1(A,B,C,D,E,F,G,J,I), 
          constr((and(K=or(select(D,C)=select(D,A+B),select(D,A+B)=0),and(not(select(I,J)=E),and(H=1+J,and(K,not(select(I,J)=0))))))).
chc_comp_false :- inv_main_0(A,B,C,D,E,F), 
          constr((and(~ (select(F,D)=0),select(C,B)=0))).
chc_comp_false :- inv_main_0(A,B,C,D,E,F), 
          constr((and(select(F,D)=0,~ (select(C,B)=0)))).
chc_comp_false :- inv_main_0(A,B,C,D,E,F), 
          constr((and(select(F,D)=0,and(select(C,B)=0,not(C=F))))).
chc_comp_false :- inv_main_1(A,B,C,D,E,F,G,H,I), 
          constr((and(J=not(select(D,A+B)=0),and(select(D,C)=select(D,A+B),and(select(I,H)=0,J))))).
chc_comp_false :- inv_main_1(A,B,C,D,E,F,G,H,I), 
          constr((and(not(select(I,H)=0),and(select(I,H)=E,select(D,A+B)=0)))).
chc_comp_false :- inv_main_1(A,B,C,D,E,F,G,H,I), 
          constr((and(and(select(D,C)=select(D,A+B),not(select(I,H)=0),select(I,H)=E,J,K),and(J=or(not(C= - 1+F),not(D=I)),K=not(select(D,A+B)=0))))).
ff :- chc_comp_false, constr((true)).

