% Automatically generated by smt2map




:- pred end_query.
:- pred inv_main_0(int,int,int,int,array(int),int,int,int,int,array(int)).
:- mode inv_main_0(in,in,in,in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

end_query :- 
          constr((and(and(A,not(select(B,C)=D),E=C,not(F=0),G=D,H=I,not(J=0),J=F,K=B),A=(select(store(K,H,select(K,E)),E)=G)))).
end_query :- 
          constr((and(not(select(A,B)=C),and(not(D=0),and(E=0,and(E=D,and(F=C,and(G=B,and(H=I,J=A))))))))).
end_query :- 
          constr((and(and(not(A),select(B,C)=D,E=C,not(F=0),G=D,H=I,not(J=0),J=F,K=B),A=(select(store(K,H,select(K,E)),E)=G)))).
end_query :- 
          constr((and(and(not(A),not(B=0),B=C,C=0,D=E,F=G,H=I,J=K),A=(select(store(J,H,select(J,F)),F)=D)))).
end_query :- 
          constr((and(and(A,select(B,C)=D,E=F,G=C,not(H=0),I=D,not(J=0),J=H,or(not(E=F),K),L=B),and(A=(select(store(L,E,select(L,G)),G)=I),K=not(store(L,E,select(L,G))=store(B,F,select(B,C))))))).
end_query :- 
          constr((and(and(A,B=C,D=E,F=G,H=0,not(I=0),I=H,or(not(F= - 1),J),K=L),and(A=(select(store(K,F,select(K,D)),D)=B),J=not(store(K,F,select(K,D))=L))))).
end_query :- 
          constr((and(and(select(A,B)=C,not(D=0),E=0,E=D,F=C,G=B,H=I,or(not(- 1=I),J),K=A),J=not(K=store(A,I,select(A,B)))))).
inv_main_0(A,B,C,D,E,F,G,H,I,J) :- 
          constr((and(and(E=store(K,L,select(K,A)),J=store(M,N,select(M,O)),not(P),not(select(M,O)=F),G=1+O,C= - 1+Q,A=O,not(I=0),L=N,not(Q=0),Q=I,B=F,D=1+L,H=1+N,K=M),P=(select(store(K,L,select(K,A)),A)=B)))).
end_query :- inv_main_0(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(select(J,G)=F,not(I=1),not(C=0),or(not(D=H),not(K)),L=B),and(K=(store(E,D,select(E,1+A))=store(J,H,select(J,G))),L=select(store(E,D,select(E,1+A)),1+A))))).
end_query :- inv_main_0(A,B,C,D,E,F,G,H,I,J), 
          constr((and(and(I=1,not(C=0),or(not(D= - 1),not(K)),L=B),and(K=(store(E,D,select(E,1+A))=J),L=select(store(E,D,select(E,1+A)),1+A))))).
end_query :- inv_main_0(A,B,C,D,E,F,G,H,I,J), 
          constr((and(K=not(E=store(J,H,select(J,G))),and(not(I=1),and(C=0,and(or(not(- 1=H),K),select(J,G)=F)))))).
end_query :- inv_main_0(A,B,C,D,E,F,G,H,I,J), 
          constr((and(I=1,and(C=0,not(E=J))))).
inv_main_0(A,B,C,D,E,F,G,H,I,J) :- inv_main_0(K,B,L,M,N,F,O,P,Q,R), 
          constr((and(and(S,not(T=B),not(select(R,O)=F),I= - 1+Q,A=1+K,not(Q=1),not(L=0),C= - 1+L,G=1+O,D=1+M,H=1+P,J=store(R,P,select(R,O))),and(S=(E=store(N,M,select(N,1+K))),T=select(store(N,M,select(N,1+K)),1+K))))).
inv_main_0(A,B,C,D,E,F,G,H,I,J) :- inv_main_0(K,B,L,M,N,F,G,H,I,J), 
          constr((and(and(not(O=B),A=1+K,not(L=0),C= - 1+L,D=1+M,or(I=1,select(J,G)=F),P),and(O=select(store(N,M,select(N,1+K)),1+K),P=(E=store(N,M,select(N,1+K))))))).
inv_main_0(A,B,C,D,E,F,G,H,I,J) :- inv_main_0(A,B,C,D,E,F,K,L,M,N), 
          constr((and(O=select(store(E,D,select(E,1+A)),1+A),and(not(select(N,K)=F),and(G=1+K,and(not(M=1),and(H=1+L,and(I= - 1+M,and(or(C=0,O=B),J=store(N,L,select(N,K))))))))))).
ff :- end_query, constr((true)).

