% Automatically generated by smt2map




:- pred 'main@linear_search.exit.split'.
:- pred 'main@.lr.ph.i.preheader'(array(int),int).
:- mode 'main@.lr.ph.i.preheader'(in,in).
:- pred 'main@.lr.ph.i'(array(int),int,int,int,int,array(int)).
:- mode 'main@.lr.ph.i'(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@.lr.ph.i.preheader'(A,B) :- constr((true)).
'main@.lr.ph.i'(A,B,C,D,E,F) :- 'main@.lr.ph.i.preheader'(G,H), 
          constr((and(I=E+4*J,and(D=1+K,and(L=store(G,B,0),and(A=store(L,B,D),and(F=store(M,I,3),and(not(E=<0),and(or(not(N),not(O),P=0),and(or(not(N),not(O),C=P),and(or(not(I=<0),E=<0),and(or(not(O),and(N,O)),and(O=true,Q=H))))))))))))).
'main@.lr.ph.i'(A,B,C,D,E,F) :- 'main@.lr.ph.i'(A,B,G,D,E,F), 
          constr((and(H=ite(I>=0,or(not(D=<I),not(D>=0)),and(not(D=<I),not(0=<D))),and(J=E+4*G,and(K=select(F,J),and(not(E=<0),and(or(not(L),not(M),not(N)),and(or(not(L),not(O),P=I),and(or(not(L),not(O),C=P),and(or(not(L),not(O),Q),and(or(not(J=<0),E=<0),and(or(not(O),and(L,O)),and(or(not(L),R=(S=20)),and(or(not(L),Q=H),and(or(not(L),S=1+G),and(or(not(L),I=ite(R,- 1,S)),and(or(not(L),and(L,N)),and(O=true,M=(K=3))))))))))))))))))).
'main@linear_search.exit.split' :- 'main@.lr.ph.i'(A,B,C,D,E,F), 
          constr((and(and(G=E+4*C,H=select(F,G),not(E=<0),or(not(I),and(J,K),and(L,M)),or(not(L),not(M),N=O),or(not(L),not(M),P=N),or(not(L),not(M),not(Q)),or(not(L),not(R),not(K)),or(not(J),not(K),S=C),or(not(J),not(K),P=S),or(not(J),not(K),R),or(not(G=<0),E=<0),or(not(I),T=U),or(not(I),not(T=V)),or(not(I),W=select(A,B)),or(not(I),not(X)),or(not(I),V),or(not(Y),and(Y,I)),or(not(L),Z=(A1=20)),or(not(L),Q=B1),or(not(L),A1=1+C),or(not(L),O=ite(Z,- 1,A1)),or(not(L),and(L,K)),or(L,not(M)),or(not(J),K),Y=true,R=(H=3)),and(U=ite(P>=0,or(not(W=<P),not(W>=0)),and(not(W=<P),not(0=<W))),B1=ite(O>=0,or(not(D=<O),not(D>=0)),and(not(D=<O),not(0=<D))))))).
ff :- 'main@linear_search.exit.split', constr((true)).

