% Automatically generated by smt2map




:- pred 'main@verifier.error.split'.
:- pred 'main@bb35.i'(int,array(int),int,int).
:- mode 'main@bb35.i'(in,in,in,in).
:- pred 'main@entry'(int).
:- mode 'main@entry'(in).
:- pred 'main@bb21.i'(int,array(int),int,int,array(int),int).
:- mode 'main@bb21.i'(in,in,in,in,in,in).
:- pred 'main@bb11.i'(int,int,array(int),int,int,array(int)).
:- mode 'main@bb11.i'(in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A) :- constr((true)).
'main@bb11.i'(A,B,C,D,E,F) :- 'main@entry'(G), 
          constr((~ ((E=<0)=H)&(I=true&(H=true&(and(J,I)&(not(I)&(B=K&(not(I)&(not(J)&(K=0&(not(I)&(not(J)&(C=L&(not(I)&(not(J)&(L=M&(not(I)&(not(J)&(~ (D=<0)&(~ (A=<0)&N=G)))))))))))))))))))).
'main@bb11.i'(A,B,C,D,E,F) :- 'main@bb11.i'(A,G,H,D,E,F), 
          constr((~ ((E=<G)=I)&(J=true&(and(K,L)&(not(K)&(not(A=<0)&(not(K)&(M=A+G&(not(K)&(N=1+G&(not(K)&(O=store(H,M,42)&(not(K)&(and(K,J)&(not(J)&(B=P&(not(J)&(not(K)&(P=N&(not(J)&(not(K)&(C=Q&(not(J)&(not(K)&(Q=O&(not(J)&(not(K)&(not(K)&(I&(not(L)&(not(K)&(A=<0&not(M=<0))))))))))))))))))))))))))))))))).
'main@bb21.i'(A,B,C,D,E,F) :- 'main@bb11.i'(A,G,B,D,F,H), 
          constr((~ ((F=<G)=I)&(J=true&(and(K,J)&(not(J)&(not(I)&(not(J)&(not(K)&(L=0&(not(J)&(not(K)&(C=L&(not(J)&(not(K)&(M=H&(not(J)&(not(K)&(E=M&(not(J)&not(K)))))))))))))))))))).
'main@bb21.i'(A,B,C,D,E,F) :- 'main@bb21.i'(A,B,G,D,H,F), 
          constr((~ ((F=<G)=I)&(J=true&(and(K,L)&(not(K)&(not(D=<0)&(not(K)&(not(A=<0)&(not(K)&(M=select(B,N)&(not(K)&(O=1+G&(not(K)&(P=D+G&(not(K)&(N=A+G&(not(K)&(Q=store(H,P,M)&(not(K)&(and(K,J)&(not(J)&(R=O&(not(J)&(not(K)&(C=R&(not(J)&(not(K)&(S=Q&(not(J)&(not(K)&(E=S&(not(J)&(not(K)&(not(L)&(I&(not(K)&(D=<0&(not(P=<0)&(not(K)&(not(N=<0)&(not(K)&A=<0))))))))))))))))))))))))))))))))))))))))).
'main@bb35.i'(A,B,C,D) :- 'main@bb21.i'(E,F,G,A,B,D), 
          constr((~ ((D=<G)=H)&(I=true&(and(J,I)&(not(I)&(not(J)&(not(I)&(not(H)&(C=K&(not(I)&(not(J)&(K=0&(not(I)&not(J)))))))))))))).
'main@bb35.i'(A,B,C,D) :- 'main@bb35.i'(A,B,E,D), 
          constr((~ ((D=<E)=F)&(G=true&(F=true&(and(H,I)&(not(H)&(J=1+E&(not(H)&(and(H,G)&(not(G)&(and(I,K)&(not(I)&(not(A=<0)&(not(I)&(L=A+E&(not(I)&(M=select(B,L)&(not(I)&(N=(M=42)&(not(I)&(C=O&(not(G)&(not(H)&(O=J&(not(G)&(not(H)&(not(I)&(not(H)&(N&(A=<0&(not(L=<0)&not(I)))))))))))))))))))))))))))))))).
'main@verifier.error.split' :- 'main@bb35.i'(A,B,C,D), 
          constr((~ ((D=<C)=E)&(E=true&(F=true&(and(F,G)&(not(F)&(and(G,H)&(not(G)&(and(H,I)&(not(H)&(and(J,I)&(not(I)&(not(A=<0)&(not(I)&(K=select(B,L)&(not(I)&(L=A+C&(not(I)&(M=(K=42)&(not(I)&(not(I)&(not(M)&(not(H)&(A=<0&(not(L=<0)&not(I)))))))))))))))))))))))))).
ff :- 'main@verifier.error.split', constr((true)).

