% Automatically generated by smt2map




:- pred 'main@_bb'(int,int,int,array(int),int,array(int)).
:- mode 'main@_bb'(in,in,in,in,in,in).
:- pred 'main@_bb4'(int,array(int),int,array(int),int).
:- mode 'main@_bb4'(in,in,in,in,in).
:- pred 'main@verifier.error.split'.
:- pred 'main@_bb6'(int,array(int),int,int,array(int),int,int).
:- mode 'main@_bb6'(in,in,in,in,in,in,in).
:- pred 'main@_bb11'(int,array(int),int,array(int),int,int,int,int).
:- mode 'main@_bb11'(in,in,in,in,in,in,in,in).
:- pred 'main@entry'(int,array(int)).
:- mode 'main@entry'(in,in).
:- pred 'main@_bb7'(int,array(int),int,int,int,array(int),int,int).
:- mode 'main@_bb7'(in,in,in,in,in,in,in,in).
:- pred 'main@_bb10'(int,array(int),int,array(int),int,int,int).
:- mode 'main@_bb10'(in,in,in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

'main@entry'(A,B) :- constr((true)).
'main@_bb'(A,B,C,D,E,F) :- 'main@entry'(A,F), 
          constr((~ (B=<0)&(G=true&(and(H,G)&(not(G)&(D=I&(not(G)&(not(H)&(I=J&(not(G)&(not(H)&(C=K&(not(G)&(not(H)&(K=0&(not(G)&not(H))))))))))))))))).
'main@_bb'(A,B,C,D,E,F) :- 'main@_bb'(A,B,G,H,E,F), 
          constr((I=(J=and(not(5=<G),G>=0))&(I&(K=true&(or(not(L),and(L,M))&(or(not(L),not(B=<0))&(or(not(L),N=store(H,O,P))&(or(not(L),Q=1+G)&(or(not(L),O=B+G)&(or(not(L),R=A)&(or(not(K),and(L,K))&(or(not(L),not(K),D=S)&(or(not(L),not(K),S=N)&(or(not(L),not(K),C=T)&(or(not(L),not(K),T=Q)&(or(not(M),not(L),J)&or(not(O=<0),not(L),B=<0))))))))))))))))).
'main@_bb4'(A,B,C,D,E) :- 'main@_bb'(F,A,G,B,C,D), 
          constr((H=(I=and(not(5=<G),G>=0))&(H&(J=true&(or(not(J),and(J,K))&(or(not(K),L)&(or(not(K),and(K,M))&(or(not(K),not(A=<0))&(or(not(K),N=4+A)&(or(not(K),O=select(B,N))&(or(not(K),L=(O=0))&(or(not(K),not(J),P=0)&(or(not(K),not(J),E=P)&(or(not(K),not(I),not(M))&or(not(N=<0),not(K),A=<0))))))))))))))).
'main@_bb4'(A,B,C,D,E) :- 'main@_bb4'(A,B,C,D,F), 
          constr((G=(H=0)&(I=true&(and(I,J)&(not(I)&(and(J,K)&(not(J)&(L=1+F&(not(J)&(A=<0&(not(M=<0)&(N=L&(not(I)&(not(J)&(E=N&(not(I)&(not(J)&(not(G)&(not(K)&(not(J)&(~ (A=<0)&(H=select(B,M)&M=A+F)))))))))))))))))))))).
'main@_bb6'(A,B,C,D,E,F,G) :- 'main@_bb4'(A,B,D,E,G), 
          constr((H=(I=0)&(J=true&(and(K,J)&(not(J)&(A=<0&(not(L=<0)&(not(K)&(H&(not(J)&(F=M&(not(J)&(not(K)&(C=N&(not(J)&(not(K)&(M=0&(not(J)&(not(K)&(N=0&(not(J)&(not(K)&(~ (A=<0)&(I=select(B,L)&L=A+G)))))))))))))))))))))))).
'main@_bb6'(A,B,C,D,E,F,G) :- 'main@_bb7'(A,B,H,D,I,E,J,G), 
          constr((K=(L=and(not(2=<I),I>=0))&(K&(M=true&(or(not(N),and(N,O))&(or(not(N),P=1+H)&(or(not(M),and(N,M))&(or(not(N),not(M),F=Q)&(or(not(N),not(M),C=R)&(or(not(N),not(M),Q=J)&(or(not(N),not(M),R=P)&or(not(N),not(L),not(O))))))))))))).
'main@_bb10'(A,B,C,D,E,F,G) :- 'main@_bb6'(A,B,H,C,D,E,I), 
          constr((J=ite(H>=0,or(not(I=<H),not(I>=0)),and(not(I=<H),not(0=<I)))&(K=J&(L=true&(or(not(L),and(M,L))&(or(not(L),not(K),not(M))&(or(not(M),not(L),F=N)&(or(not(M),not(L),G=O)&(or(not(M),not(L),N=0)&or(not(M),not(L),O=0)))))))))).
'main@_bb10'(A,B,C,D,E,F,G) :- 'main@_bb11'(A,B,C,D,E,H,I,J), 
          constr((K=(L=and(not(2=<I),I>=0))&(K&(M=true&(or(not(N),and(N,O))&(or(not(N),P=1+H)&(or(not(M),and(N,M))&(or(not(N),not(M),F=Q)&(or(not(N),not(M),G=R)&(or(not(N),not(M),Q=J)&(or(not(N),not(M),R=P)&or(not(N),not(L),not(O))))))))))))).
'main@_bb7'(A,B,C,D,E,F,G,H) :- 'main@_bb6'(A,B,C,D,F,I,H), 
          constr((J=ite(C>=0,or(not(H=<C),not(H>=0)),and(not(H=<C),not(0=<H)))&(K=J&(L=true&(or(not(L),and(L,M))&(or(not(M),not(L),K)&(or(not(M),not(L),G=N)&(or(not(M),not(L),E=O)&(or(not(M),not(L),O=0)&or(not(M),not(L),N=I)))))))))).
'main@_bb7'(A,B,C,D,E,F,G,H) :- 'main@_bb7'(A,B,C,D,I,F,J,H), 
          constr((K=(L=and(not(2=<I),I>=0))&(K&(M=true&(or(not(M),and(M,N))&(or(not(N),and(N,O))&(or(not(N),not(D=<0))&(or(not(N),not(A=<0))&(or(not(N),P=1+I)&(or(not(N),Q=J+R)&(or(not(N),R=ite(S,1,0))&(or(not(N),T=select(F,U))&(or(not(N),U=D+I)&(or(not(N),V=select(B,W))&(or(not(N),W=A+C)&(or(not(N),S=(V=T))&(or(not(N),not(M),G=X)&(or(not(N),not(M),E=Y)&(or(not(N),not(M),Y=P)&(or(not(N),not(M),X=Q)&(or(not(N),L,not(O))&(or(not(N),D=<0,not(U=<0))&or(not(N),A=<0,not(W=<0)))))))))))))))))))))))).
'main@_bb11'(A,B,C,D,E,F,G,H) :- 'main@_bb10'(A,B,C,D,E,I,F), 
          constr((J=(K=0)&(L=true&(and(L,M)&(not(L)&(not(N=<0)&(A=<0&(not(J)&(not(L)&(not(M)&(G=O&(not(L)&(not(M)&(O=0&(not(L)&(not(M)&(H=P&(not(L)&(not(M)&(P=I&(not(L)&(not(M)&(~ (A=<0)&(K=select(B,N)&N=A+F)))))))))))))))))))))))).
'main@_bb11'(A,B,C,D,E,F,G,H) :- 'main@_bb11'(A,B,C,D,E,F,I,J), 
          constr((K=(L=and(not(2=<I),I>=0))&(K&(M=true&(or(not(M),and(M,N))&(or(not(N),and(N,O))&(or(not(N),not(C=<0))&(or(not(N),not(A=<0))&(or(not(N),P=1+I)&(or(not(N),Q=J+R)&(or(not(N),R=ite(S,1,0))&(or(not(N),T=select(D,U))&(or(not(N),U=C+I)&(or(not(N),V=select(B,W))&(or(not(N),W=A+F)&(or(not(N),S=(V=T))&(or(not(N),not(M),G=X)&(or(not(N),not(M),X=P)&(or(not(N),not(M),H=Y)&(or(not(N),not(M),Y=Q)&(or(not(N),L,not(O))&(or(not(N),C=<0,not(U=<0))&or(not(N),A=<0,not(W=<0)))))))))))))))))))))))).
'main@verifier.error.split' :- 'main@_bb10'(A,B,C,D,E,F,G), 
          constr((H=(I=0)&(J=true&(not(K)&(not(L)&(and(L,M)&(not(L)&(N=ite(O,1,0)&(not(L)&(O=(F=E)&(not(L)&(and(L,P)&(not(P)&(and(J,Q)&(not(J)&(and(Q,R)&(not(Q)&(and(R,S)&(not(R)&(T&(not(S)&(and(P,S)&(not(S)&(T=(N=0)&(not(S)&(A=<0&(not(U=<0)&(not(M)&(H&(not(L)&(~ (A=<0)&(I=select(B,U)&U=A+G)))))))))))))))))))))))))))))))).
ff :- 'main@verifier.error.split', constr((true)).

