% Automatically generated by smt2map




:- pred new11(int,int,int,int,int,int,int).
:- mode new11(in,in,in,in,in,in,in).
:- pred new4(int,int,int,int,int,int).
:- mode new4(in,in,in,in,in,in).
:- pred new10(int,int,int,int,int,int).
:- mode new10(in,in,in,in,in,in).
:- pred new9(int,int,int,int,int,int).
:- mode new9(in,in,in,in,in,in).
:- pred new8(int,int,int,int,int,int).
:- mode new8(in,in,in,in,in,in).
:- pred new7(int,int,int,int,int,int).
:- mode new7(in,in,in,in,in,in).
:- pred new2(int,int,int,int,int,int).
:- mode new2(in,in,in,in,in,in).
:- pred new6(int,int,int,int,int,int).
:- mode new6(in,in,in,in,in,in).
:- pred new5(int,int,int,int,int,int).
:- mode new5(in,in,in,in,in,in).
:- pred new3(int,int,int,int,int,int).
:- mode new3(in,in,in,in,in,in).
:- pred new1(int).
:- mode new1(in).
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new11(A,B,C,D,E,F,G) :- constr((and(H=0,and(I=0,B=0)))).
new11(A,B,C,D,E,F,G) :- new4(A,C,H,I,F,G), 
          constr((and(B>=1,and(J=1,and(H=1+D,and(K=1,and(I=1+E,L=0))))))).
new11(A,B,C,D,E,F,G) :- new4(A,C,H,I,F,G), 
          constr((and(B=< - 1,and(J=1,and(H=1+D,and(K=1,and(I=1+E,L=0))))))).
new10(A,B,C,D,E,F) :- new11(A,G,B,C,D,E,F), constr((and(C>=0,and(H=0,G=1)))).
new10(A,B,C,D,E,F) :- new11(A,G,B,C,D,E,F), constr((and(C=< - 1,and(H=0,G=0)))).
new9(A,B,C,D,E,F) :- new10(A,B,C,D,E,F), constr((and(A>=1,G=0))).
new9(A,B,C,D,E,F) :- new10(A,B,C,D,E,F), constr((and(A=< - 1,G=0))).
new9(A,B,C,D,E,F) :- new4(A,B,G,H,E,F), 
          constr((and(I=1,and(H=1+J,and(K=1,and(G=1+L,and(M=1,and(N= - 1+J,and(O=1,and(P= - 1+L,and(Q=1,and(R= - 2+J,and(S= - 1+J,and(T=0,and(U=0,and(D= - 2+J,and(C= - 1+L,A=0))))))))))))))))).
new8(A,B,C,D,E,F) :- new9(A,B,C,D,E,F), constr((and(B-C>=2,and(G=1,H=1+C)))).
new8(A,B,C,D,E,F) :- new10(A,B,C,D,E,F), constr((and(B-C=<1,and(G=1,H=1+C)))).
new7(A,B,C,D,E,F) :- new2(A,B,C,D,E,F), constr((true)).
new6(A,B,C,D,E,F) :- new8(A,B,C,D,E,F), constr((D-F=< - 1)).
new6(A,B,C,D,E,F) :- new7(A,B,C,D,E,F), constr((D-F>=0)).
new5(A,B,C,D,E,F) :- new6(A,B,C,D,E,F), constr((C-B=< - 1)).
new5(A,B,C,D,E,F) :- new7(A,B,C,D,E,F), constr((C-B>=0)).
new4(A,B,C,D,E,F) :- new5(A,B,C,D,E,F), constr((true)).
new3(A,B,C,D,E,F) :- new4(A,B,C,G,E,F), constr((and(C-B=< - 1,G=0))).
new2(A,B,C,D,E,F) :- new3(A,B,C,D,E,F), constr((true)).
new1(A) :- new2(A,B,C,D,E,F), constr((and(C=0,and(G=4,F= - 4+E)))).
incorrect :- new1(A), constr((A=0)).

