% Automatically generated by smt2map




:- pred new4(int,int).
:- mode new4(in,in).
:- pred new3(int).
:- mode new3(in).
:- pred new2(int).
:- mode new2(in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new4(A,B) :- constr((and(C=0,and(D=0,A=0)))).
new3(A) :- new4(B,A), constr((and(A>=5,and(C=5,B=1)))).
new3(A) :- new4(B,A), constr((and(A=<4,and(C=5,B=0)))).
new2(A) :- new3(A), constr((and(A>=11,B=10))).
new1 :- new2(A), constr((true)).
incorrect :- new1, constr((true)).

