% Automatically generated by smt2map




:- pred new9(int,int,int).
:- mode new9(in,in,in).
:- pred new2(int,int,int).
:- mode new2(in,in,in).
:- pred new8(int,int,int).
:- mode new8(in,in,in).
:- pred new7(int,int,int).
:- mode new7(in,in,in).
:- pred new6(int,int,int,int).
:- mode new6(in,in,in,in).
:- pred new5(int,int,int).
:- mode new5(in,in,in).
:- pred new4(int,int,int).
:- mode new4(in,in,in).
:- pred new3(int,int,int).
:- mode new3(in,in,in).
:- pred new1.
:- pred incorrect.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

new9(A,B,C) :- new2(D,E,F), 
          constr((and(G=1,and(D=1+A,and(F=6,and(E=1,and(H=4,and(I=4,B=4)))))))).
new9(A,B,C) :- new2(D,E,C), 
          constr((and(B>=5,and(F=1,and(D=1+A,and(E=2,G=4)))))).
new9(A,B,C) :- new2(D,E,C), 
          constr((and(B=<3,and(F=1,and(D=1+A,and(E=2,G=4)))))).
new8(A,B,C) :- new2(D,E,F), 
          constr((and(G=1,and(D=1+A,and(F=5,and(E=1,and(H=3,and(I=3,B=3)))))))).
new8(A,B,C) :- new9(A,B,C), constr((and(B>=4,D=3))).
new8(A,B,C) :- new9(A,B,C), constr((and(B=<2,D=3))).
new7(A,B,C) :- new2(D,E,F), 
          constr((and(G=1,and(D=1+A,and(F=4,and(E=3,and(H=2,and(I=2,B=2)))))))).
new7(A,B,C) :- new8(A,B,C), constr((and(B>=3,D=2))).
new7(A,B,C) :- new8(A,B,C), constr((and(B=<1,D=2))).
new6(A,B,C,D) :- constr((and(E=0,and(F=0,A=0)))).
new5(A,B,C) :- new6(D,A,B,C), constr((and(C>=7,and(E=6,D=1)))).
new5(A,B,C) :- new6(D,A,B,C), constr((and(C=<5,and(E=6,D=1)))).
new5(A,B,C) :- new6(D,A,B,C), constr((and(E=6,and(F=6,and(D=0,C=6))))).
new4(A,B,C) :- new2(D,E,F), 
          constr((and(G=1,and(D=1+A,and(F=3,and(E=2,and(H=1,and(I=1,B=1)))))))).
new4(A,B,C) :- new7(A,B,C), constr((and(B>=2,D=1))).
new4(A,B,C) :- new7(A,B,C), constr((and(B=<0,D=1))).
new3(A,B,C) :- new4(A,B,C), constr((and(A=<9,D=10))).
new3(A,B,C) :- new5(A,B,C), constr((and(A>=10,D=10))).
new2(A,B,C) :- new3(A,B,C), constr((true)).
new1 :- new2(A,B,C), constr((and(B=1,A=0))).
incorrect :- new1, constr((true)).

