; Automatically generated by map2smt

(set-logic HORN)

(declare-fun incorrect ( ) Bool)
(declare-fun new1 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new2 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)
(declare-fun new3 ( Int (Array Int Int) (Array Int Int) (Array Int Int) (Array Int Int) Int Int Int Int ) Bool)

(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M (Array Int Int)) )
    (=>
      (and (= J (+ 1 I)) (= K 1) (>= (- A I) 1) (= (select D I) L) (= (store E I L ) M) (new3 A B C D M F G H J))
      (new3 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= J 0) (<= (- G F) (- 1)) (>= H 0) (>= (- I A) 0) (>= (- A H) 1) (= (select B H) G) (= (select E H) F))
      (new3 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= J 0) (>= H 0) (>= (- I A) 0) (>= (- A H) 1) (>= (- G F) 1) (= (select B H) G) (= (select E H) F))
      (new3 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M (Array Int Int)) )
    (=>
      (and (= J (+ 1 I)) (= K 1) (>= (- A I) 1) (= (select C I) L) (= (store D I L ) M) (new2 A B C M E F G H J))
      (new2 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= J 0) (>= (- I A) 0) (new3 A B C D E F G H J))
      (new2 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) (J Int) (K Int) (L Int) (M (Array Int Int)) )
    (=>
      (and (= J (+ 1 I)) (= K 1) (>= (- A I) 1) (= (select B I) L) (= (store C I L ) M) (new1 A B M D E F G H J))
      (new1 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B (Array Int Int)) (C (Array Int Int)) (D (Array Int Int)) (E (Array Int Int)) (F Int) (G Int) (H Int) (I Int) (J Int) )
    (=>
      (and (= J 0) (>= (- I A) 0) (new2 A B C D E F G H J))
      (new1 A B C D E F G H I)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D (Array Int Int)) (E (Array Int Int)) (F (Array Int Int)) (G (Array Int Int)) (H Int) (I Int) (J Int) )
    (=>
      (and (= A 1) (= B 0) (>= C 1) (new1 C D E F G H I J B))
      incorrect
    )
  )
)

(assert (not incorrect))
(check-sat)
