% Automatically generated by smt2map




:- pred incorrect.
:- pred new1(int,array(int),array(int),int,int).
:- mode new1(in,in,in,in,in).
:- pred new2(int,array(int),array(int),int,int).
:- mode new2(in,in,in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.


