% Automatically generated by smt2map




:- pred itp1(int,int,int).
:- mode itp1(in,in,in).
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

itp1(A,B,C) :- constr((and(B=0,and(A=0,C=0)))).
itp1(A,B,C) :- itp1(D,E,F), 
          constr((or(and(A=D,B=1+E,C= - 1+F),and(A=1+D,B=E,C=1+F)))).
ff :- itp1(A,B,C), constr((and(~ (C=0),A=B))).

