% Automatically generated by smt2map




:- pred inv(int,int,int).
:- mode inv(in,in,in).
:- pred fail.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv(A,B,C) :- constr((and(or(A=0,A=1),and(or(B=0,B=1),C=0)))).
inv(A,B,C) :- inv(D,E,F), 
          constr((and(G=(C=ite(D mod 2=E mod 2,1+F,F)),and(B=3+E,and(G,A=2+D))))).
fail :- inv(A,B,C), constr((and(~ (C>=100),~ (A=<400)))).
ff :- fail, constr((true)).

