% Automatically generated by smt2map




:- pred inv(int).
:- mode inv(in).
:- pred fail.
:- pred ff.
:- query ff/0.
:- pred constr(bool).
:- mode constr(in).
:- ignore constr/1.

inv(A) :- constr((A=0)).
inv(A) :- inv(B), constr((A=ite(200=<B div 5,5+B,1+B))).
fail :- inv(A), constr((and(~ (A mod 5=0),A>=2000))).
ff :- fail, constr((true)).

