; Automatically generated by map2smt

(set-logic HORN)

(declare-fun new6 ( Int Int ) Bool)
(declare-fun new5 ( Int ) Bool)
(declare-fun new4 ( Int ) Bool)
(declare-fun new2 ( Int ) Bool)
(declare-fun new3 ( Int ) Bool)
(declare-fun new1 ( ) Bool)
(declare-fun incorrect ( ) Bool)

(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) )
    (=>
      (and (= A 0) (= C 0) (= D 0))
      (new6 A B)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) )
    (=>
      (and (= A 50) (= B 1) (= C 50) (= D 50) (new6 B A))
      (new5 A)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) )
    (=>
      (and (= B 0) (= C 50) (>= A 51) (new6 B A))
      (new5 A)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) )
    (=>
      (and (= B 0) (= C 50) (<= A 49) (new6 B A))
      (new5 A)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) )
    (=>
      (and (= A 50) (= B 50) (= C 50) (new5 A))
      (new4 A)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) )
    (=>
      (and (= B 50) (>= A 51) (new2 A))
      (new4 A)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) )
    (=>
      (and (= B 50) (<= A 49) (new2 A))
      (new4 A)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) (C Int) (D Int) )
    (=>
      (and (= B 100) (= C (+ 1 A)) (= D 1) (<= A 99) (new4 C))
      (new3 A)
    )
  )
)
(assert
  (forall ( (A Int) (B Int) )
    (=>
      (and (= B 100) (>= A 100) (new5 A))
      (new3 A)
    )
  )
)
(assert
  (forall ( (A Int) )
    (=>
      (new3 A)
      (new2 A)
    )
  )
)
(assert
  (forall ( (A Int) )
    (=>
      (and (= A 0) (new2 A))
      new1
    )
  )
)
(assert 
 (=>
      new1
      incorrect
    ))

(assert (not incorrect))
(check-sat)
